### ISSUE TITLE
Overly Restrictive Regex for Service Accounts

### ISSUE THREAD

**Issue by kylegoch** [terraform-providers/terraform-provider-google#1134]
This regex validates Service Account Ids:
https://github.com/terraform-providers/terraform-provider-google/blob/master/google/validation.go#L33

However, I have a service account that TF created that fails that check. But the SA is in my project, and referenced just fine when i do `terraform plan`, but when the `apply` happens for `google_service_account_iam_policy` the regex freaks out saying it's not valid, despite it actually being valid (and created!).

Can that regex either be ditched or made to properly accept the names for Service Accounts.

(due to the senstive nature of the SA I created, I cant share it here, sorry)

**Comment by ndmckinley** [comment]
It can't be discarded, but it can be made to accommodate whatever it's missing.  Still, to make that change, we're going to need something to go on - can you give us a fictional service account name that doesn't reveal sensitive information while still causing the regex to fail?

**Comment by kylegoch** [comment]
Why cant you discard it, and let the API handle the failure?

As it stands right now, Terraform is actually saying that something coming from Google Cloud itself is invalid. Which doesn't make a lot of sense, unless I have missed something.

**Comment by ndmckinley** [comment]
It can be very bad for some users to discover failures partway through the infrastructure creation process.  Say you're creating a large infrastructure system, and you go to change a service account name, and you make a typo which you don't notice.  You `terraform apply`, and destroy a bunch of infrastructure, then the API returns an error because of your bad service account name, and you spend a few minutes with all the infrastructure destroyed trying to find your error.  Much better to report an error when you run before we start making changes.

Can you provide any more information so we can fix the problem?

**Comment by kylegoch** [comment]
Fair enough. Let me see if I can make something that still acts weird but doesnt reveal anything.
