### ISSUE TITLE
Can't generate service_account_key for default service account

### ISSUE THREAD

**Issue by kevinconstantine** [terraform-providers/terraform-provider-google#1248]
### Terraform Version
Terraform version: 0.11.5  342c529aa58d824f2f2ed1f6ec6118059876aad0

### Affected Resource(s)
- google_compute_default_service_account
- google_service_account_key

### Terraform Configuration Files
```hcl
data "google_compute_default_service_account" "default" {}

resource "google_service_account_key" "default" {
    service_account_id  = "${data.google_compute_default_service_account.default.id}"
}

output "default_account" {
    value = "${google_service_account_key.default.name}"
```

### Debug Output
https://gist.github.com/kevinconstantine/63f84ae02731d739b11cee42fe2af5ef

### Expected Behavior
I would expect that terraform would provide me with the name of a new service_account_key for the default service account.  Ultimately I want the actual key file in json format but for the purposes of this bug report, I'm just trying to spit out the name.

### Actual Behavior
I get an error that says that the Resource 'google_service_account_key.default' not found for variable 'google_service_account_key.default.name', and in the debug output, it looks like we're doing a regex comparison of the default service account 'XXXXXXXXXX-compute@developer.gserviceaccount.com' against an expected id that ends with a regex that must end in `iam.gserviceaccount.com`  Because those two obviously don't match, we fail to generate a key and return it.

### Steps to Reproduce
1. `terraform apply`

**Comment by danawillow** [comment]
Hey @kevinconstantine, are you positive that plan output lines up with that config? That particular error would happen because it's missing a resource called `google_service_account_key.default`, but it doesn't seem to be referenced anywhere within your config so I'm not sure why it's popping up. Can you double-check for me?

**Comment by kevinconstantine** [comment]
Sorry @danawillow my mistake when I sanitized after-the-fact and missed something.  The config snippet has been updated to match the output gist.

**Comment by danawillow** [comment]
All right, there are two separate things going on here:
1. The `service_account_id` field takes the key id in the form of a link. See https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts.keys/create. Our docs don't say that at all, so I can see why that would be confusing. I'll try to update it so that it can take an email address as well.
2. Regardless of that, apparently the default service account fails our validation anyway because it follows patterns that aren't allowed when creating a service account (using a number as the first character, for example). That restriction will also have to be relaxed.

I'll work on this today. Thanks for the report!
