### ISSUE TITLE
google_container_node_pool version upgrade fails if cluster has more than one pool

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1339]
Hi there,
We have a kubernetes cluster which has three node pools.  We've successfully updated the master however updating the node_pools results in an error.

Here is the plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.hot-nodes.google_container_node_pool.elastic-pool
      version:       "1.9.6-gke.0" => "1.9.6-gke.1"

  ~ module.k8-elastic-cluster.google_container_cluster.cluster
      node_version:  "1.9.6-gke.0" => "1.9.6-gke.1"

  ~ module.warm-nodes.google_container_node_pool.elastic-pool
      version:       "1.9.6-gke.0" => "1.9.6-gke.1"
```

And here is the resulting error:
```
Error: Error applying plan:

1 error(s) occurred:

* module.k8-elastic-cluster.google_container_cluster.cluster: 1 error(s) occurred:

* google_container_cluster.cluster: googleapi: Error 400: Node pool id must be specified if cluster has more than one node pool.., badRequest

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

**Comment by Stono** [comment]
Ahhh interestingly, this was actually because we were using `node_version` on the cluster as well.

In order to get this to work we had to add `ignore_changes = ["node_version"]` then explicitly set the `version` on the `node_pool`.

I will leave this issue open for now (based on your thoughts) because i think perhaps we could add some simple validation to the plugin that is like (pseudo code):

```
if cluster.pools.length > 1 && node_version.changed then
  error "Hey, you have more than one node pool so you should be setting version on the pools instead"
```

**Comment by ndmckinley** [comment]
To make sure I understand, your preference is for the error to be clearer rather than for behavior changes?

**Comment by Stono** [comment]
Yeah it's an interesting point actually and I would like to understand your general stand point on this and if it's something you endeavour to do generally.

There are certain errors/logic that could be validated in terraform and presented as part of the plan (such as this one) and i think that is valuable because otherwise we end up with half applied plans (if we are making multiple changes), so I'm always a fan of bringing that feedback look forward.

Downside is you're effective replicating the Google API validation in your API wrapper (you could get it wrong).

What are your thoughts?

**Comment by ndmckinley** [comment]
I'm just one of the Google-side team that works on this, so I don't presume to speak for everyone, but my standpoint is that our ideal form is "very convenient API client".  To me, that means that we can clarify error messages and do field-level validation - e.g. if you type something that's 90 characters long for a project name, we can tell you "that field in the API accepts 63 characters or less".

I don't think that "we noticed that you have several node pools, and consequently we interpreted your input differently than if you had only had one" is within our purview - that sort of complex validation is just waiting to bitrot out of step with the GCP APIs.  I see the upside in avoiding half-applying plans for configs with obtuse and hard-to-spot errors ... but the borderline-inevitable downside of people down the line with valid configs being spuriously rejected is worse, in my opinion.

I *do* think "we noticed you got a 400 error with the text 'Node pool id must be specified if cluster has more than one node pool', so we tell you to make this change on the pool resource instead of on the cluster resource" is within that purview.  Another example that came up this week, to hopefully clarify where I stand: if you try to set a DNS record but provide a bad RRData, I don't want us to validate it ahead of time, but I'd be pretty happy to spit out a list of the fields you should include once a 400 'invalid rrdata' error comes back.

**Comment by Stono** [comment]
@ndmckinley I've mulled this over more and I agree with your points, you've tipped me onto your side of the fence when it comes to duplicating validation in terraform.
