### ISSUE TITLE
Protocol Forwarding (google_compute_target_instance)

### ISSUE THREAD

**Issue by ellmkay** [terraform-providers/terraform-provider-google#1341]
This feature is now GA:
https://cloud.google.com/compute/docs/protocol-forwarding

Target instances are a nice way of not having to configure instance-groups for single-instance use-cases. 

So from my understanding, implementing a new resource called: 
google_compute_target_instance
and then supporting it within google_compute_forwarding_rule would make sense.

**Comment by outworlder** [comment]
Rather than mere convenience of not having to configure instance groups, there is at least one situation where they are actually required.

For some load balancer protocols, you cannot have target-groups and you *have to* use target instances. ICMP is one example (more information here: https://cloud.google.com/load-balancing/docs/forwarding-rules)

I have just had to supplement Terraform with some gcloud scripts to get around this limitation, there was no other way.

**Comment by danawillow** [comment]
Added in https://github.com/GoogleCloudPlatform/magic-modules/pull/1690
