### ISSUE TITLE
europe-north1 breaks things

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-google#1348]
Following:
```
data "google_compute_network" "default" {
  name = "default"
}

data "google_compute_subnetwork" "subnetworks" {
  count  = "${length(data.google_compute_network.default.subnetworks_self_links)}"
  name   = "${data.google_compute_network.default.name}"
  region = "${element(split("/", data.google_compute_network.default.subnetworks_self_links[count.index]), 8)}"
}
```

explodes with:

```
* data.google_compute_subnetwork.subnetworks[4]: data.google_compute_subnetwork.subnetworks.4: Error reading Subnetwork Not Found : default: googleapi: Error 400: Invalid value for field 'region': 'europe-north1'. Unknown region., invalid
```

Apparently a new region is coming that is not supported by everything yet...

**Comment by matti** [comment]
fixed for now with:
```
locals {
  google_pls = [
    "europe-west1",
  ]
}

data "google_compute_subnetwork" "subnetworks" {
  count  = "${length(local.google_pls)}"
  name   = "${data.google_compute_network.default.name}"
  region = "${local.google_pls[count.index]}"
}
```

**Comment by ndmckinley** [comment]
Ah, the downside of client-side validation.  :)  I'll see where europe-north1 is valid but not accepted.

**Comment by ndmckinley** [comment]
Oh, I see, that will be the official name of the new Finland region.
https://cloud.google.com/compute/docs/regions-zones/

It's not listed as officially launched - are you a member of the early-access group, or are the docs strangely out of date?

**Comment by matti** [comment]
Nope, the api (ds) just started to return that and it brakes everything.

**Comment by ndmckinley** [comment]
I'm sorry, I'm a little confused, so let me make sure I've got this right.  You're saying that your code config N data sources for subnetworks, one for each of the subnetworks in your network, that one of those subnetworks has the region europe-north1, and that when trying to do a `Read` on that, you got a 400 because subnetworks don't support requests in that region even though the network is telling you that there is a subnetwork there already.  I agree that that's a problem, but I think my original assessment is wrong - this probably has nothing to do with terraform-provider-google.  Let me raise that internally and see what people have to say.
