### ISSUE TITLE
Unnecessary check in resourceComputeInstanceRead

### ISSUE THREAD

**Issue by maikzumstrull** [terraform-providers/terraform-provider-google#141]
### Terraform Version

0.9.8

### Affected Resource(s)
google_compute_instance

### Expected Behavior

Terraform should notice that different disks are attached to an instance than it expects. It should be possible to ignore this condition with lifecycle/ignore_changes.

### Actual Behavior

Terraform errors out trying to refresh the instance.

As far as I can tell, this check: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance.go#L852-L854 is simply not necessary. In any case, the result should be a resource specification that TF can diff, not error on refresh.

**Comment by danawillow** [comment]
Hey @maikzumstrull, thanks for the report. I'm doing some large changes around the way we handle disks right now (see #122 and #123 for an idea of where we're headed) and that got check got caught up in the middle of them. I'm going to focus my efforts on the larger change rather than trying to fix this check specifically, but I appreciate the report!

**Comment by maikzumstrull** [comment]
The problematic code has [moved around a bit](https://github.com/terraform-providers/terraform-provider-google/blob/41248230efbf108436095b2b3cf89f4364e08c65/google/resource_compute_instance.go#L1117-L1119), but it's still in there and still breaks operations really badly (because Terraform errors out instead of just reporting "this instance looks different than expected" and considering that in the plan). This also causes #355.
