### ISSUE TITLE
Updating from a zonal to a regional cluster does not recreate the resource (it should)

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#1450]
At the moment there is no migration path from zonal to regional clusters from Google.

Support for regional was added in this provider recently, however i've noticed when setting region (and unsetting zone) on an existing cluster, it does not taint the resource for recreation.

Going from:
```
resource "google_container_cluster" "cluster" {
  zone = "europe-west1-c"
}
```

To:
```
resource "google_container_cluster" "cluster" {
  region = "europe-west1"
}
```

Results in:
```
  ~ module.kubernetes.google_container_cluster.cluster
      region:                                "" => "europe-west1"
```

Expected:
```
  ~ module.kubernetes.google_container_cluster.cluster (new resource required)
      region:                                "" => "europe-west1" (forces new resource)
```

**Workaround** 
Do a `terraform destroy -target=module.kubernetes.google_container_cluster.cluster` first

**FYI**
This appears to be working as expected on the node_pool resource:

```
-/+ module.kubernetes.google_container_node_pool.custom-pool (new resource required)
      id:                                    "europe-west1-c/delivery-platform/custom-pool" => <computed> (forces new resource)
      region:                                "" => "europe-west1" (forces new resource)
```

**Comment by ndmckinley** [comment]
Thanks for the report!  These resources are tough to get perfect.

Question: are those first two examples precise?  I suspect it can't be quite that simple, because `zone` is marked as `ForceNew`.  Although `region` is not, the two are marked as conflicting, so moving to a region would force you to set the `zone` to `""`, which would force a new resource.  Are you using provider-level zone or region, rather than setting them on the resources, or do we have a more confusing bug?

**Comment by Stono** [comment]
I think we may have a more confusing bug as zone = "" did not trigger the new resource either.

I am back in the office later today so i'll repeat the process just to validate.

**Comment by ndmckinley** [comment]
Thanks!  Please let me know.  :)
