### ISSUE TITLE
Add support for scopes, labels and tags on GKE Node Pool

### ISSUE THREAD

**Issue by stonith** [terraform-providers/terraform-provider-google#161]
**Terraform Version**

Terraform v0.10.0-dev (9706042ddd51b85a46e23356536a1d812efa5a38+CHANGES)

**Affected Resource(s)**

google_container_node_pool

**References**

https://cloud.google.com/container-engine/docs/node-pools#creating_a_node_pool
https://cloud.google.com/sdk/gcloud/reference/beta/container/node-pools/create

Already added to google_container_cluster in #7

**Comment by holoGDM** [comment]
Hello, any progress with it?

**Comment by selmanj** [comment]
I'm working on adding labels support currently; will relate PR when it's ready.

**Comment by holoGDM** [comment]
Hello again, is there some time in which i can expect it? I see there is new version of Terraform but this ticket is still not finished (same options for cluster creation ware implemented in next version from raising ticket). Just asking, because this options will be really helpfull (without it i can't fully finished our automation) for our config.

**Comment by selmanj** [comment]
Actually this was added in #184 and should be available next release.
