### ISSUE TITLE
Change Cloud Bigtable name -> id to clarify its meaning

### ISSUE THREAD

**Issue by mbrukman** [terraform-providers/terraform-provider-google#1673]
In [the Bigtable docs](https://github.com/terraform-providers/terraform-provider-google/blob/7e64b3f1c1124f612f784800f0a168a47ca877c5/website/docs/r/bigtable_instance.html.markdown), an instance is identified by the parameter `name` but a cluster is identified by `cluster_id`:

```hcl
resource "google_bigtable_instance" "instance" {
  name         = "tf-instance"
  cluster_id   = "tf-instance-cluster"
  zone         = "us-central1-b"
  num_nodes    = 3
  storage_type = "HDD"
}
```

Later on, the optional parameter `display_name` for an instance is also discussed, which defaults to `name` if not specified.

However, what is called `name` for an instance should actually be an instance `id` since it is a unique identifier, with restrictions (e.g., no spaces, all lowercase, globally unique in the project, etc.), and the `display_name` is the human-readable string that does not. When they're called `name` and `display_name`, that is confusing.

Note that this would be a breaking change, so it would be best coupled with a fix for issue #1672 (also a breaking change).

**Comment by emilymye** [comment]
Sadly, we can't use "id" as a parameter in Terraform schemas as it is reserved for the system. 

It'd be possible to use `instance_id` instead of `name` but that seems fairly redundant (given the resource name already has instance). Also, pretty much all resources in Terraform (not just this provider) use `name` instead of `id` across the board.  The only exceptions tends to be when "name" is being used/reserved by GCP, and I'd wouldn't be surprised if changing `name` to `instance_id` would actually be more confusing to users.
