### ISSUE TITLE
google_container_cluster: removing additional_zones block doesn't update cluster

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#1710]
Hi there,

When removing the 'additional_zones' block from a google_container_cluster resource, no changes are applied to the cluster. If you set it to [], the cluster is updated.

### Terraform Version
Google provider 0.15.0

### Affected Resource(s)
google_container_cluster

### Expected Behavior
It should remove the additional zones that were configured

### Actual Behavior
Nothing

### Steps to Reproduce
- create cluster in europe-west4-b and add this block:
```hcl
additional_zones = [
  "europe-west4-a",
]
```
- terraform apply to modify the cluster to run in the addtional zone as well.
- now remove the whole `additional_zone` block
- run terraform again, no updates will be done
- when you add back this code, the cluster is updated.
```hcl
additional_zones = [
]
```

**Comment by danawillow** [comment]
Unfortunately, this is a limitation of Terraform that we can't easily get around. One of the things we can set on our schema is `Computed`, which means "if there is no value set for this field, then use whatever the API returns". We need to have this for regional clusters, because if the user doesn't set any additional zones, GKE will pick zones in that cluster, and we don't want Terraform to try to reset that back to zero. This has the side effect of not allowing full removals. I don't expect this to change any time soon, so until then, I'd recommend using the empty list workaround that you mentioned.

**Comment by rolandkool** [comment]
Hi Dana,

Thanks for the feedback. I guess we need to keep limitation in mind in our setup. I'll close this issue.
