### ISSUE TITLE
Terraform does not set source_tags and target_tags to empty list for google_compute_firewall resource.

### ISSUE THREAD

**Issue by roman8422** [terraform-providers/terraform-provider-google#1715]
Hello,

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- google_compute_firewall

### Terraform Configuration Files
```hcl
resource "google_compute_network" "default" {
  name                    = "foobar"
  auto_create_subnetworks = "true"
}

resource "google_compute_firewall" "tcp80" {
  name    = "tcp80"
  network = "foobar"

  allow {
    protocol = "tcp"
    ports    = ["80"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["web"]
}
```

### Expected Behavior
After deleting target_tags line tags should be deleted from firewall rule and the rule should be applied to all instances on the specified network

### Actual Behavior
Terraform shows that tag will be deleted but after apply it is still in place.
```
Terraform will perform the following actions:

  ~ google_compute_firewall.tcp80
      target_tags.#:         "1" => "0"
      target_tags.365508689: "web" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```
Same issue with source_tags.

### Steps to Reproduce
1. use code from above and run `terraform apply`
2. delete line `target_tags   = ["web"]`
3. run `terraform apply` again

**Comment by Chupaka** [comment]
Same issue with `source_ranges`

**Comment by vishen** [comment]
This looks like it is happening because we are using the [PATCH compute firewall request](https://cloud.google.com/compute/docs/reference/rest/v1/firewalls/patch), and because the [firewall struct in Golang](https://godoc.org/google.golang.org/api/compute/v0.beta#Firewall) has 
```golang
TargetTags []string `json:"targetTags,omitempty"`
```

the `targetTag` (and a bunch of other ones) get filtered out if empty, thus causing google to think this field should remain unchanged.

Looking at other resources that use PATCH it looks like they do the [following](https://github.com/terraform-providers/terraform-provider-google/blob/8c2f47ba6943b8ba9407597f1953528882cd3889/google/resource_storage_bucket.go#L368)

```golang
// resource_storage_bucket
if d.HasChange("logging") {
	if v, ok := d.GetOk("logging"); ok {
		sb.Logging = expandBucketLogging(v.([]interface{}))
	} else {
		sb.NullFields = append(sb.NullFields, "Logging")
	}
}
```

but [resource_google_compute](https://github.com/terraform-providers/terraform-provider-google/blob/8c2f47ba6943b8ba9407597f1953528882cd3889/google/resource_compute_firewall.go#L397) does the following

``` golang
// resource_compute_firewall
var targetTags []string
if v := d.Get("target_tags").(*schema.Set); v.Len() > 0 {
	targetTags = make([]string, v.Len())
	for i, v := range v.List() {
		targetTags[i] = v.(string)
	}
}
```

So I believe all we have to do is add these fields to the `Firewall.NullFields` (which seems to be what this field is for) similar to how the `resource_storage_bucket` does it?
