### ISSUE TITLE
Resource labels on Kubernetes Engine not purged when no resource labels specified

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#1785]
Hi there,

### Terraform Version
Terraform 0.11.7
Google Provider 1.16.1

### Affected Resource(s)
- google_container_cluster

### Terraform Configuration Files
Any HCL containing a container cluster definition, but without the `resource_labels` parameter.

### Expected Behavior
Because no labels are specified, any existing label on the container cluster should be purged. The terraform apply shows it is removing the labels, but after the apply, the labels are still there.

### Actual Behavior
It should purge all existing labels

**Comment by danawillow** [comment]
Hmm, @paddycarver can you look at this? I thought the whole point of 1.16.1 was to fix removing resource labels from clusters.

**Comment by paddycarver** [comment]
Yes and no. v1.16.1 was to solve a panic when updating labels. It looks like this is just a case of a missing `ForceSendFields`. I've put an item on my TODO list to fix that.

**Comment by rileykarson** [comment]
Since there's no config / debug logs provided and `1.16` was a long time ago, I'm closing this as outdated. If this is still an issue can you file again @rolandkool?

According to https://github.com/terraform-providers/terraform-provider-google/issues/1758, it can take a while for resource labels to be updated. Is it possible that waiting 1-2h applies the change?
