### ISSUE TITLE
Add import functionality for Google Compute Engine resources

### ISSUE THREAD

**Issue by jvrplmlmn** [terraform-providers/terraform-provider-google#182]
### Terraform Version

```bash
$ terraform --version
Terraform v0.10.0-beta2-dev
```

### Affected Resource(s)

Most Google Compute Engine resources lack the import functionality. An example: `google_compute_instance`.

**Comment by danawillow** [comment]
Hey @jvrplmlmn, just for prioritization: which resources in particular would you like import support on? Obviously we'd like to include it for all of them but this will at least help us come up with an ordering.

**Comment by jvrplmlmn** [comment]
Hi @danawillow, right now I'm mainly interested in `google_compute_instance`.

Is there any guide on how to write an importer function for Terraform? I might be able to contribute a patch if I get some guidance 😃

**Comment by danawillow** [comment]
Self-assigning but @rosbo will be working on this.

@jvrplmlmn there isn't a guide per se, but take a look at https://github.com/terraform-providers/terraform-provider-google/pull/40 for an example. `google_compute_instance` isn't quite as straightforward though, because it currently reads from state in the read function (you can tell from the `d.Get(...)`s which won't work for import, so it'll need to stop doing that first.

**Comment by rosbo** [comment]
Most compute resources now have import support. `google_compute_instance` doesn't have import support yet but there is a specific issue to address it (#269).

If there is a specific resource for which you would like to have import support, please open a new issue for that specific resource.

Closing this issue.
