### ISSUE TITLE
Recent changes to kms_key_ring and kms_crypto_key may be breaking

### ISSUE THREAD

**Issue by sethvargo** [terraform-providers/terraform-provider-google#1895]
### Affected Resource(s)
- `kms_key_ring`
- `kms_crypto_key`

### Expected Behavior
The new ID changes should be backwards compatible and not force new resource creation.

### Actual Behavior
The new ID format may include a domain prefix. Existing Terraform configurations with persisted state that had a domain prefix, will now detect changes and drift as a result. Terraform will try to destroy and re-create the crypto_key/key_ring... the problem is that those resources are immutable, so Terraform will delete all existing cryptoKeyVersions (under the hood on KMS), leaving the user super super sad.

### Important Factoids
This is a breaking change that, if affected and applied, would cause customers to lose all their encryption key versions. They would be forced to contact Google support to restore the key versions, and their encrypted data would be unrecoverable until GCP support restored their crypto key versions.

### References
- GH-1865

**Comment by danawillow** [comment]
As we talked about internally, this is not quite the case. GH-1865 does not change the format the ID is stored in. Furthermore, changing the ID of a resource does not cause a diff on that resource- only on its dependencies if they specifically depend on the ID field.

We could have mitigated this back when the actual change was submitted (in April, GH-1337) by adding MigrationFuncs to all resources that we thought might potentially depend on the id field, but we would have been pretty likely to forget one. We can't do anything about it now though, since at this point everyone's states will be using the new ID format. The best real solution is to add a `self_link` or `full_name` or _something_ field to the resources so that users don't have to decide between depending on the id (dangerous because it could change) or reconstructing the full name of the resource (annoying, makes the config look less nice), and update our examples to use the new field.

**Comment by sethvargo** [comment]
I personally vote for `self_link`. What do you think? Do you want me to open another issue to talk about that or change this one?

**Comment by ndmckinley** [comment]
My plan is to add `self_link`, yep.  No need for another issue, I'm going to do it in the PR that's already open.

**Comment by ndmckinley** [comment]
But like Dana says, those domain prefix changes make those resources possible for people with legacy domain-prefixed projects.  There's no chance of them changing an existing resource since people with legacy domain-prefixed projects couldn't create those resources before that change.  The issue you're describing (the id format change) happens on upgrade from 0.1.7 to 0.1.8 (March 12, 2018 -> March 19, 2018).  I'm going to go ahead and close it when #1876 goes in, considering the `self_link` change to resolve the underlying concern that people might choose to rely on ID for lack of a better easy option.
