### ISSUE TITLE
Standardize `id` formats and make it a useful value

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#1927]
We have a bunch of examples and tests that depend on the ID field, but we don't want our users to have to know the format of that field, and we want the ability to change that format at will. This issue entails making sure that every test and documentation example that relies on the id of a resource no longer does that, potentially adding new fields to existing resources that represent what we currently store as the id.

**Comment by danawillow** [comment]
Just talked to @rileykarson about this, and a future world might end up going the exact opposite of this, where we use ID as the field to interpolate on for references to other resources, basically always. That becomes tricky for resources where, some things want different formats, but we might be able to get it working for most cases and document when it doesn't.

What we don't want, though, is a world where you _sometimes_ use the id. This issue still holds for now, but loosely.

**Comment by rileykarson** [comment]
Let's thing about this more when we get closer to `3.0.0` and can use MM for sweeping changes across even more of the codebase than we can today. Tagged with a milestone.

**Comment by paddycarver** [comment]
Assigning this to myself to follow up with the core team about what rules exist around IDs that we need to make sure to follow.

**Comment by paddycarver** [comment]
So I followed up with the core team, and it sounds like we can treat the ID field as a normal field, with these caveats:

* I believe we can only _really_ change the ID when creating a resource, or when refreshing a resource. That is, all the rules from #4328 apply here.
* Because 0.11 treated ID as special sometimes, and the shims are unpredictable, we want to make sure we test the functionality with some rigor to make sure the implementation doesn't have any weirdness. But this should be treated _more_ like a regular field in future versions of the SDK, not _less_, so I think treating it as a regular field ourselves is moving in the right direction.

**Comment by paddycarver** [comment]
Leaving this issue assigned to me until we can set a new owner for it tomorrow (that owner may still end up being me, but let's at least talk about it.)

**Comment by rileykarson** [comment]
@slevenick: Updated the title to reflect reality, feel free to change it if I've got it wrong or you've got a better idea 🙂
