### ISSUE TITLE
Add support for BigQuery Scheduling Queries

### ISSUE THREAD

**Issue by marcin-kolda** [terraform-providers/terraform-provider-google#2028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Add support for BigQuery [Scheduling Queries](https://cloud.google.com/bigquery/docs/scheduling-queries). It would be great to have scheduled queries created in TF on top of BigQuery views or tables, e.g. when you setup new app, you can create tables, views and queries which could do some periodical aggregation, etc.

### New or Affected Resource(s)

* google_bigquery_scheduled_query

**Comment by cemo** [comment]
Is there something blocking this issue? Since the release of 2.0.0 (February 12, 2019), there is only *single* new terraform resource. I really can not understand how things are prioritised. BigQuery is the most important part of Google Cloud when it is compared with others but there are waiting many improvements and new resources related to it.

**Comment by danawillow** [comment]
I think the API that this request is looking at is this one: https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs, though there's going to be some design work there to figure out how closely to map that vs what is seen in the console (the "params" field being the biggest difference, since there are no guidelines that I can find about what actually goes there, though I'm pretty sure one of the things would be the query to schedule).

@cemo to answer your question, our team does many things besides just creating new resources: we add new capabilities to old ones, fix bugs, do infrastructure improvements, review incoming PRs, and also spend time on other things that come up, like making sure the provider was compatible with 0.12. I recognize that it's frustrating not to see the features you want. If you have someone at GCP or HashiCorp (an account manager, sales rep, customer engineer, etc.) that you work with, feel free to contact them about the features you're looking for. Alternatively, we happily accept PRs against the provider, though for new resources like this we prefer to generate them with [magic modules](https://github.com/GoogleCloudPlatform/magic-modules).
