### ISSUE TITLE
GKE/google_container_cluster storing credentials in the state file

### ISSUE THREAD

**Issue by directionless** [terraform-providers/terraform-provider-google#2039]
I'm looking at using terraform for some simple GKE setup tasks. Create project, create cluster, etc. I notice that on completion, terraform stores the `master_auth.0.client_key` in the state file. I find that somewhat concerning.

I know secret data in state files has been a long running pain point. I'm wondering if you have any thoughts here. Could we have an option to suppress this, or is it needed? I expect runtime authorization to use the same credentials as the google provider.

**Comment by ndmckinley** [comment]
You're right to be concerned, but I'm sorry, this is best discussed on Terraform core.  I know there is a long-running discussion on the best way to deal with secrets.  As for the Google provider specifically, there is nothing special available to us that will keep secrets more safe than any other Terraform provider.

If you need to do something about it right now, I might recommend remote state, placing the state somewhere where you feel confident about the ACLs.  This at least prevents you from accidentally committing the state into a git repo and sending it somewhere world-readable.

I am going to close this issue, though, because unfortunately there's no option available to us, the Google provider, to solve it.

**Comment by directionless** [comment]
There is no place I feel comfortable keeping those secrets. Google provides me with a fine authentication layer, I see no reason to re-invent it for this.

So far, the best I've got it to rotate the GKE credentials after the TF run. [1](https://cloud.google.com/kubernetes-engine/docs/how-to/credential-rotation). It's workable, but needing post-setup scripting makes the value add from TF much smaller.

**Comment by directionless** [comment]
Anyhow thanks for commenting. I feel frustrated, but I recognize it's a core issue

**Comment by directionless** [comment]
Anyhow thanks for commenting. I feel frustrated, but I recognize it's a core issue
