### ISSUE TITLE
Deprecate things that should be deprecated

### ISSUE THREAD

**Issue by danawillow** [terraform-providers/terraform-provider-google#2143]
* [x] Beta fields
* [x] Instance Group Manager
* [x] `resource_compute_instance.network_interface.access_config.assigned_nat_ip`
* [x] cloudfunctions_function doesn't match the API in an important way (we have trigger_topic and trigger_bucket instead of the more expressive event_trigger, which has more options) and doesn't match the API in a couple less important ways (trigger_http as a string instead of https_trigger as an object with just a string in it; source_archive_bucket and source_archive_object instead of source_archive_url). We should fix all of them.
* [x] bigtable_instance is doing something funky with clusters and hiding them. We should deprecate cluster_id, and expose a cluster sub-block, maybe even a cluster resource.

And probably some more things!

**Comment by paddycarver** [comment]
* [ ] cloudfunctions_function doesn't match the API in an important way (we have trigger_topic and trigger_bucket instead of the more expressive event_trigger, which has more options) and doesn't match the API in a couple less important ways (trigger_http as a string instead of https_trigger as an object with just a string in it; source_archive_bucket and source_archive_object instead of source_archive_url). We should fix all of them.
