### ISSUE TITLE
Clarify documentation around service_account_id expected value for  google_service_account_iam_* resources

### ISSUE THREAD

**Issue by walterdolce** [terraform-providers/terraform-provider-google#2180]
The [documentation](https://www.terraform.io/docs/providers/google/r/google_service_account_iam.html#service_account_id) says:

> service_account_id - (Required) The service account id to apply policy to.

And that is all fine. But when it comes to having something like the following:
```
resource "google_service_account" "k8s_cluster_service_account" {
  account_id   = "${var.k8s_cluster_service_account_id}"
  display_name   = "${var.k8s_cluster_service_display_name}"
}

resource "google_service_account_iam_member" "k8s_cluster_service_account_log_writer" {
  service_account_id = "${google_service_account.k8s_cluster_service_account.account_id}"
  role        = "roles/logging.logWriter"
  member      = "serviceAccount:${google_service_account.k8s_cluster_service_account.email}"
}

resource "google_service_account_iam_member" "k8s_cluster_service_account_metric_writer" {
  service_account_id = "${google_service_account.k8s_cluster_service_account.account_id}"
  role        = "roles/monitoring.metricWriter"
  member      = "serviceAccount:${google_service_account.k8s_cluster_service_account.email}"
}

resource "google_service_account_iam_member" "k8s_cluster_service_account_monitoring_viewer" {
  service_account_id = "${google_service_account.k8s_cluster_service_account.id}"
  role        = "roles/monitoring.viewer"
  member      = "serviceAccount:${google_service_account.k8s_cluster_service_account.email}"
}

resource "google_service_account_iam_member" "k8s_cluster_service_account_storage_object_viewer" {
  service_account_id = "${google_service_account.k8s_cluster_service_account.account_id}"
  role        = "roles/storage.objectViewer"
  member      = "serviceAccount:${google_service_account.k8s_cluster_service_account.email}"
}
```

This would fail because:
> "service_account_id" ("whatever-the-id") doesn't match regexp "projects/(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))/serviceAccounts/((?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))@appspot.gserviceaccount.com|[0-9]{1,20}-compute@developer.gserviceaccount.com|[a-z](?:[-a-z0-9]{4,28}[a-z0-9])@[-a-z0-9\\.]{1,63}\\.iam\\.gserviceaccount\\.com$)"

As you can see I naturally went for using `account_id`. Little did I know I had to just use `id`.

This took me a bit of time away just to understand what I was doing wrong. It shouldn't happen.

Do you think the documentation would clearly state that the `id`, rather than `account_id` or `unique_id` is expected to be set in `service_account_id`?

I'm happy to send a PR for this so that this gets off your shoulders.

Thank you.

**Comment by walterdolce** [comment]
I ended up using `google_project_iam_member`.

**Comment by sergei-ivanov** [comment]
@walterdolce your example would not work, and in your case `google_project_iam_member` was indeed the correct resource to use.
You tried to use `k8s_cluster_service_account` as both a _resource_ and an _identity_ (both GCP and Terraform documentation explain the difference pretty well). So you were effectively trying to say _"grant `k8s_cluster_service_account` a `roles/logging.logWriter` role over **itself**"_. And when you read it this way it does not make much sense. AFAIK the only possible roles that it is possible to grant on service account resources are `roles/iam.serviceAccountXXXXX` roles. For example, you can grant another member (a user, a group or another service account) `roles/iam.serviceAccountUser` role over your service account, so that they can "run as" your service account.
If you want to grant a certain project role (e.g. `roles/logging.logWriter`) _to_ your service account, you use project IAM bindings.
