### ISSUE TITLE
Add Service Peering to Beta Provider

### ISSUE THREAD

**Issue by yhuang** [terraform-providers/terraform-provider-google#2308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Support for service peering is missing.  As users start looking to convert their Cloud SQL instances to use private IPs, this capability, which is available in `gcloud beta` will become a necessity.

### New or Affected Resource(s)

google_compute_network
google_compute_global_address
google_compute_network_peering

### Potential Terraform Configuration

```tf
resource "google_compute_global_address" "managed_services" {
  name          = "managed-services"
  provider      = "google-beta"

  address_type  = "INTERNAL"
  network       = "${var.network_self_link}"
  prefix_length = "16"
  project       = "${var.project_id}"
  purpose       = "VPC_PEERING"
}

resource "google_service_peering" "connect" {
  network = "${var.network_self_link}"
  range = "${google_compute_global_address.managed_services.range}"
  service = "servicenetworking.googleapis.com"
  project = "${var.project}"
}
```

### References
* https://cloud.google.com/sdk/gcloud/reference/beta/services/vpc-peerings/connect
* https://cloud.google.com/sql/docs/mysql/private-ip
* https://cloud.google.com/vpc/docs/configure-private-services-access#allocating-range

**Comment by chrisst** [comment]
We added support for VPC_PEERING to the global address object https://www.terraform.io/docs/providers/google/r/compute_global_address.html#purpose a month ago to support ip range reservation. It should be available in the latest version of the beta provider right now.

Can you take a look and let me know what functionality is missing?

**Comment by yhuang** [comment]
Thank you for the quick reply @chrisst.  I did come across that new capability in beta last night, and that was what set me on the path to start exploring Cloud SQL private IP in Terraform.  The work done so far by the beta resource covers this gcloud command:
```
gcloud beta compute addresses create [RESERVED_RANGE_NAME] \
    --global \
    --purpose=VPC_PEERING \
    --prefix-length=16 \
    --description=[DESCRIPTION] \
    --network=[VPC_NETWORK] \
```
I can confirm that resource from the beta provider works.  What is missing is support for the next step:
```
gcloud beta services vpc-peerings connect \
    --service=servicenetworking.googleapis.com \
    --ranges=[RESERVED_RANGE_NAME] \
    --network=[VPC_NETWORK] \
    --project=[PROJECT_ID]
```

**Comment by yhuang** [comment]
@chrisst : I also have a related question to how the GCP Terraform provider team envisions Service VPC Peering to work.  One of the resources I included as part of the potential Terraform configuration is actually what I have right now in my code base:

```
resource "google_compute_global_address" "managed_services" {
  name          = "managed-services"
  provider      = "google-beta"

  address_type  = "INTERNAL"
  network       = "${var.network_self_link}"
  prefix_length = "16"
  project       = "${var.project_id}"
  purpose       = "VPC_PEERING"
}
``` 
The resource from the beta provider expects the network self-link, not the subnetwork self-link.  In the [google_compute_network documentation](https://www.terraform.io/docs/providers/google/r/compute_network.html), I see this deprecation warning:
```
ipv4_range - (Optional) If set to a CIDR block, uses the legacy VPC API with the specified range. This API is deprecated. If set, auto_create_subnetworks must be explicitly set to false.
```
If that is the case, people who wish to use Service VPC Peering with Terraform will not be able to specify the exact CIDR block they would like to use.  In my case, Terraform saw the four subnetworks I have currently associated with my VPC network are `10.128.0.0/24`, ``10.129.0.0/24`, `10.130.0.0/24`, and ``10.131.0.0/24`.  After processing that resource declaration, Terraform reported that GCP reserved the address `10.205.0.0`.  Since I specified a prefix_length of `16`, I am assuming the entire range of `10.205.0.0/16` has been cordoned off in preparation for the Service VPC Peering.  I would like to understand how GCP made the decision to start the reservation at the address `10.205.0.0` and not another.

**Comment by chrisst** [comment]
@yhuang I'm not totally sure what the goals of the network team are but I'll try and answer as best I can (Also cc @rileykarson who knows a bit more about this then me). 

I believe that the aim for compute networks is to either have the network created in 'auto' mode or 'custom' mode. Auto would create and manage all your subnetworks for you with [predetermined ip ranges](https://cloud.google.com/vpc/docs/vpc#ip-ranges) and custom will allow you to manage the ip ranges yourself. You can use `google_compute_subnetwork` in order to manage the CIDR blocks in that case.

The problem with `ipv4_range` on compute network is it forces us to create a `legacy` style network which is something the network cloud teams are trying to move people away from.
more info: 
https://cloud.google.com/vpc/docs/legacy
https://cloud.google.com/vpc/docs/using-legacy

**Comment by rileykarson** [comment]
I've managed to delete a half-finished reply twice so far so this will be a little brief/rough 🤦‍♀️ 

I half-understand what's going on here, so I'll write it down more so that I can refer back to it in the future, and also to (hopefully) clarify everything here.

---

@chrisst is correct that `ipv4_range` is just for legacy networks. The equivalent in a custom subnetwork is `google_compute_subnetwork.ip_cidr_range`.

---

Just to clarify with `google_compute_global_address`, what it does is reserve a range of IPs inside a VPC network so that subnetworks can't use that range. It's a weird overloading of the `google_compute_address`/`google_compute_global_address` resources which normally reserve single IPs.

When you specify a specific `google_compute_global_address.address` while reserving a range, GCP will attempt to reserve an IP range from that IP address onwards for as long as the `prefix_length`. If you don't explicitly specify it, GCP will choose an arbitrary range that is not in use.

So GCP will never select a range that overlaps with an existing subnetwork if you don't specify an `address`, and the request will fail if it would make an invalid one.

We missed the use case of selecting a specific `address` when implementing range reservation - we'll need to add support for it to `google_compute_global_address`.

Reserving an IP range is useful because it means you can guarantee two VPC networks can peer (by blocking out the other's IP range), or you can guarantee the IP of an external service won't be overwritten.

---

Finally, the `gcloud services` command's REST equivalent is https://cloud.google.com/service-infrastructure/docs/service-networking/reference/rest/ I think. We need to support that new top-level API as well.

**Comment by chrisst** [comment]
Yeah I agree it's a bit of a strange overload. However I'm not sure what you mean when you say we missed the `address` in `google_compute_global_address`?

**Comment by rileykarson** [comment]
It's still computed so it can't be set by the user: https://github.com/terraform-providers/terraform-provider-google/blob/2.0.0/google/resource_compute_global_address.go#L69

**Comment by chrisst** [comment]
I think everything is now merged in so that this feature can be used. Let me know if we overlooked anything and I'll reopen
