### ISSUE TITLE
Update docs to describe Bigtable functionality

### ISSUE THREAD

**Issue by mbrukman** [terraform-providers/terraform-provider-google#241]
Per [this Tweet](https://twitter.com/danawillow/status/889592066128265216) from @danawillow:

> terraform-provider-google v0.1.2 is out! Upgrade for Bigtable support, more importable resources, and more! https://releases.hashicorp.com/terraform-provider-google/

there is now Bigtable support in Terraform, which is very exciting!

However, Terraform's [Google provider docs](https://www.terraform.io/docs/providers/google/) don't mention Bigtable at all. It looks like [this file](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/google.erb) needs to be updated to describe the new functionality.

**Comment by danawillow** [comment]
Yeah, we're still working out how the website gets updated after the split. If you'll notice, that file does have bigtable in it, it just hasn't been pushed to the website yet.

@apparentlymart @radeksimko @catsby can one of you help get the website updated?

**Comment by rileykarson** [comment]
In the meantime as well, Github is able to render the markdown files we use for the docs nicely enough; [Google Bigtable Instance](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/bigtable_instance.html.markdown) and [Google Bigtable Table](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/bigtable_table.html.markdown) are both able to be previewed.

**Comment by apparentlymart** [comment]
Hi @mbrukman, @danawillow,

Currently the website is still reflecting the state of things for Terraform 0.9, and thus the version of the Google provider that was bundled inside it.

The new docs will get released as part of the 0.10 final release, since that's the point where these new features will become available to most people.

In principle we could push some selected changes to the current website, but we'd leaned towards not doing that because most people are currently using the provider versions bundled inside 0.9 and so it felt like it'd be confusing to have the website reflect features that require special steps to get access to (either using the 0.10.0-rc1 build or manually installing the separated plugin with 0.9.)

Sorry for all the assorted weirdness as we transition to 0.10. This ought to get smoother once we get over this little hump and _everything_ is ready to deal with separated providers.

**Comment by danawillow** [comment]
Thanks @apparentlymart! Closing this issue, then.

**Comment by mbrukman** [comment]
The docs have been published and are now available at:

* https://www.terraform.io/docs/providers/google/r/bigtable_instance.html
* https://www.terraform.io/docs/providers/google/r/bigtable_table.html

However, there appear to have been some issues on the terraform.io website this morning, and these pages were first there, then 404, and now the first one is visible, but the second one is still returning a 404 even though it's linked from this page:

* https://www.terraform.io/docs/providers/google/index.html
