### ISSUE TITLE
Unable to bootstrap gke cluster w/ service account

### ISSUE THREAD

**Issue by jhoblitt** [terraform-providers/terraform-provider-google#2540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

At present, it is not possible to create a new gke cluster, a service account w/ a role to access said cluster, and configure the kubernetes provider within the same tf configuration as `provider.kubernetes.client_key` expects a PEM format string while the `resource.google_service_account_key.*.private_key` attribute is only configurable to return either PKCS12 or JSON.  While the JSON document format does contain a PEM format private key, tf will not be able to natively parse JSON until 0.12 ships.

### New or Affected Resource(s)

* `google_service_account_key.private_key_type` would need an additional enum value along the lines of `TYPE_PEM`.

### Potential Terraform Configuration

```tf
provider "google" {
  project = "${var.google_project}"
}

resource "google_container_cluster" "gke_std" {
...
}

resource "google_service_account" "admin" {
  project = "${var.google_project}"
  account_id   = "${var.name}"
  display_name = "${var.name} Admin RBAC"
}

resource "google_service_account_key" "admin" {
  service_account_id = "${google_service_account.admin.name}"
  private_key_type = "TYPE_PEM_FILE"
}

provider "kubernetes" {
  host                   = "${google_container_cluster.gke_std.endpoint}"
  client_key             = "${base64decode("${google_service_account_key.admin.private_key}")}"
  cluster_ca_certificate = "${base64decode("${google_container_cluster.gke_std.master_auth.0.cluster_ca_certificate}")}"
}

# kubenertes_* resources...
```

**Comment by ndmckinley** [comment]
I'd love to be able to make these things work together, but I'm afraid that that logic just doesn't belong in the GCP terraform provider.  I'm sorry - you'll either need to wait for 0.12 (which should be soon - the second alpha was recently released, and we'll be in the beta as soon as it's ready), or re-file this request in the Kubernetes provider, to allow k8s to import JSON or PKCS12.

**Comment by jhoblitt** [comment]
@imduffy15 I hope you will reconsider this feature proposal.  tf `0.12` is practically months away from being production ready as it will take time for plugins to be updated.  I also don't think it would be appropriate for the `kubernetes` provider to parse various vendor specific string formats to extract credentials.  Where as `google_service_account_key` being able to return a `PEM` formatted string is generically useful for interacting with the google cloud API for any client that isn't using `gcloud`.  Further, the implementation complexity is trivial as the google cloud API is already returning a `PEM` formatted certificate.  This solves a real problem as kludges are present even in official examples. Eg., https://github.com/GoogleCloudPlatform/gke-rbac-demo/blob/master/terraform/modules/instance/main.tf#L22-L24

**Comment by ndmckinley** [comment]
I hear you about it being a real problem - I agree, and it would be good to solve this.  I can see that the workarounds are pretty ugly.  I also hear you that vendor-specific imports don't seem like they fit in the k8s provider - I can see that it doesn't match the project design.

Along those same lines, we're not going to be able to add this to `google_service_account_key` because it doesn't fit with our project's design, but I do think there are terraform-idiomatic solutions that fit within the design goals of this provider.

For instance, I do think it'd be pretty reasonable for the k8s provider to have a data source that takes in a bunch of different cred formats and outputs a `PEM` format.  If they're not willing or able to do that, it seems to me that a similar data source could fit into terraform-provider-google - take in the JSON-format string, output the PEM-format.  We'd normally accept a PR along those lines, but as it happens, our next big release is tied to `0.12` (we'll be doing a bugfix release next week, but this wouldn't be in by then).  So, even if we implemented it, it wouldn't get released until the problem was already solved.

Since there are workarounds right now (e.g. that null-data-source situation you linked to), and since the problem will be solved for good as soon as any other solution could plausibly be released, I'm going to leave the issue closed.  It's a good idea, and it's a real problem.  We just can't really solve it right now because of the `0.12` circumstances.
