### ISSUE TITLE
google_container_cluster - kubernetes_dashboard should be disabled by default

### ISSUE THREAD

**Issue by vbhavsar** [terraform-providers/terraform-provider-google#2547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

GKE dashboard [is deprecated](https://cloud.google.com/kubernetes-engine/docs/concepts/dashboards) but it [is enabled by default](https://www.terraform.io/docs/providers/google/r/container_cluster.html#kubernetes_dashboard). It should be disabled by default.

### New or Affected Resource(s)

* google_container_cluster

### References

https://cloud.google.com/kubernetes-engine/docs/concepts/dashboards

**Comment by ndmckinley** [comment]
Thanks for the deprecation notice.  As for enabled-by-default, that's to do with the API.

It's enabled by default, because if you don't include a [`KubernetesDashboard`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.KubernetesDashboard) block to send, it's interpreted as the empty block `{}`, which has a default value for all attributes.  The default value of a boolean is `false`, so it's interpreted as `disabled: false`.  Contrast [`LegacyAbac`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.LegacyAbac), which has `enabled` instead of `disabled` - so that one is disabled by default (`enabled: false`).

**Comment by vbhavsar** [comment]
@ndmckinley Would you be okay if `kubernetes_dashboard` was set to `disabled: true` in absence of `KubernetesDashboard` block?

This would mean adding an `else` block to https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_container_cluster.go#L1594-L1600 that sets `disabled: true`.

**Comment by ndmckinley** [comment]
I'd definitely accept that PR, but you'd need to hurry - it's a breaking change and we have a 2.0.0 release pending in the next week or so.

**Comment by vbhavsar** [comment]
Is the release schedule available somewhere? When is 2.0.0 scheduled to be released? I'd like the fix to be part of that release.

**Comment by ndmckinley** [comment]
2.0.0 has been a very special case.  It was released this morning.  Going forward, we expect to release minor versions approximately every two weeks, usually on Tuesdays, and major versions every 8-12 months.  We are currently discussing whether we can exempt this request from our breaking change policies, because it represents a change to the underlying API (a deprecation).

**Comment by rileykarson** [comment]
This is disabled by default now.
