### ISSUE TITLE
Trying to create 2 clusters for BigTable Replication

### ISSUE THREAD

**Issue by michyliao** [terraform-providers/terraform-provider-google#2664]
Hi,

I am trying to terraform a BigTable instance with replication enabled. I have tried to create 2 clusters in the config of

```
resource "google_bigtable_instance" "instance" {
  name         = "tf-instance"
  cluster {
    cluster_id   = "tf-instance-cluster-1"
    zone         = "us-central1-b"
    num_nodes    = 3
    storage_type = "HDD"
  }


cluster {
    cluster_id   = "tf-instance-cluster-2"
    zone         = "us-central1-c"
    num_nodes    = 3
    storage_type = "HDD"
  }
}
```

Let me know how to enable this.. I cannot find any documentation w.r.t this.

Thanks

**Comment by rileykarson** [comment]
Hey @michyliao! That bug was about enabling multiple clusters- we've added support at HEAD in our `2.0.0` branch, but our `2.0.0` release is blocked on an upstream release of the Terraform `0.12` beta. When we release `2.0.0`, creating 2 clusters will be possible. Unfortunately, we don't have a strong estimate on when we'll be able to cut `2.0.0` as we're waiting on that upstream release.
