### ISSUE TITLE
google_compute_firewall does not remove source ranges when a source_tag is set

### ISSUE THREAD

**Issue by filipVisko** [terraform-providers/terraform-provider-google#2713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.11
+ provider.google v1.20.0
```

### Affected Resource(s)

* google_compute_firewall

#### This config does not wipe away the `source_range`

```tf
resource "google_compute_firewall" "testing-intinf-prometheus-wmi-exporter-allow-from-internal" {
  name    = "testing-intinf-prometheus-wmi-exporter-allow-from-internal"
  network = "${google_compute_network.testing-intinf.self_link}"
  direction = "INGRESS"
  allow {
    protocol = "tcp"
    ports = ["9100"]
  }
  source_tags = ["testing-intinf"]
  target_tags = ["testing-intinf"]
  priority = 1000
  depends_on = ["google_compute_network.testing-intinf"]
}
```

#### This config is a workaround that _does_ wipe away the `source_range`

```
resource "google_compute_firewall" "testing-intinf-prometheus-wmi-exporter-allow-from-internal" {
  name    = "testing-intinf-prometheus-wmi-exporter-allow-from-internal"
  network = "${google_compute_network.testing-intinf.self_link}"
  direction = "INGRESS"
  allow {
    protocol = "tcp"
    ports = ["9100"]
  }
  source_tags = ["testing-intinf"]
  target_tags = ["testing-intinf"]
  source_ranges= []
  priority = 1000
  depends_on = ["google_compute_network.testing-intinf"]
}
```

### Starting state of resource

The firewall rule has no source or target tags, and has a source range of `0.0.0.0/0`. See below for TF config.

### Expected Behavior

According to the documentation for [google_compute_firewall#source_ranges](https://www.terraform.io/docs/providers/google/r/compute_firewall.html#source_ranges) I would expect the first config file to remove the source_range from the firewall rule.

### Actual Behavior

* The source and target tags are added as expected.
* The source range is _not_ removed; unexpected.

### Steps to Reproduce

```tf
resource "google_compute_network" "testing-intinf" {
  name = "testing-intinf"
  auto_create_subnetworks = "false"
}

resource "google_compute_subnetwork" "testing-intinf" {
  name          = "testing-intinf"
  ip_cidr_range = "10.52.0.0/20"
  network       = "${google_compute_network.testing-intinf.self_link}"

  region        = "europe-west1"

  secondary_ip_range {
    range_name = "k8s-pods"
    ip_cidr_range = "10.52.16.0/20"
  }
  secondary_ip_range {
    range_name = "k8s-services"
    ip_cidr_range = "10.52.32.0/20"
  }
}

resource "google_compute_firewall" "testing-intinf-prometheus-wmi-exporter-allow-from-internal" {
  name    = "testing-intinf-prometheus-wmi-exporter-allow-from-internal"
  network = "${google_compute_network.testing-intinf.self_link}"
  direction = "INGRESS"
  allow {
    protocol = "tcp"
    ports = ["9100"]
  }
  priority = 1000
  depends_on = ["google_compute_network.testing-intinf"]
}
```

1. Save the above to a file 
1. `terraform init`
1. `terraform apply`

### References

* #0000

**Comment by andor44** [comment]
As an extension of this issue: when changing an ingress rule to an egress rule `source_range` is also not removed, _plus_ your workaround cannot be used because terraform will complain about conflicting `source_range` and `destinatio_range`s.

Perhaps it is as simple as removing `source_range` when it is not provided but maybe ingress -> egress change should force new resource.

**Comment by ndmckinley** [comment]
I agree - ingress to egress should be `ForceNew`.  I'll make that change.

The rest of that is somewhat complicated.  Since those fields are `Computed` (we made that choice in order to allow the use of defaults), the current value in GCP is used if they are not explicitly set.  Removing a field with a `Computed` value is a challenge (it requires you to explicitly set the value to the empty value), and it's not something we can really fix in this provider.  I hear you that it's possible to wind up in a broken state with this resource, though, and I'll make the change suggested.

I'll also remove that `source_range`/`destination_range` `ConflictsWith`, so the workaround will be valid for that case.
