### ISSUE TITLE
Feature Request: scratch_disk's count

### ISSUE THREAD

**Issue by rafaelgaspar** [terraform-providers/terraform-provider-google#281]
### Terraform Version
```bash
$ terraform -v
Terraform v0.10.0
```

### Affected Resource(s)
- google_compute_instance

### Terraform Configuration Files
```hcl
resource "google_compute_instance" "node" {
  ...

  scratch_disk {
    interface = "NVME"
  }

  scratch_disk {
    interface = "NVME"
  }

  scratch_disk {
    interface = "NVME"
  }

  scratch_disk {
    interface = "NVME"
  }

  ...
}
```

### Expected Behavior
It would be nice to be able to use something like this:

```hcl
resource "google_compute_instance" "node" {
  ...

  scratch_disk {
    count = 4
    interface = "NVME"
  }

  ...
}
```

This would also enable the possibility to implement a conditional on the scratch disks, like:

```hcl
resource "google_compute_instance" "node" {
  ...

  scratch_disk {
    count = "${var.local_ssd ? 1 : 0}"
    interface = "NVME"
  }

  ...
}
```

**Comment by danawillow** [comment]
So this is actually a broader issue- core terraform only supports `count` on top level resources, and not on blocks within resources. Adding a separate `count` field to the resource would be problematic, since people might expect it to behave similarly to the resource `count` field, which has some special properties. I'm going to go ahead and close this out since it's just not feasible at the moment, but feel free to reopen if I'm misunderstanding. In the meantime, if you'd like to file an issue against https://github.com/hashicorp/terraform for supporting count on blocks within resources, I'm sure the core maintainers would appreciate the feedback :)
