### ISSUE TITLE
Allow redis_instance to infer region from location_id

### ISSUE THREAD

**Issue by rsalmond** [terraform-providers/terraform-provider-google#2929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Allow `google_redis_instance` to infer the `region` parameter when `location_id` is specified.

### New or Affected Resource(s)

* google_redis_instance

### Potential Terraform Configuration

```tf
resource "google_redis_instance" "my_redis" {
  name               = "my_redis"
  memory_size_gb     = 1
  tier               = "BASIC"
  location_id        = "us-central1-b"
}
```

### Details

At present, when no region or zone is specified at the provider level, the above code produces the following error.

```
Error: Error applying plan:

1 error(s) occurred:

* google_redis_instance.my_redis: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```

**Comment by danawillow** [comment]
relabeling this as a bug since it appears on first glance that the location_id field is completely ignored in favor of region, which shouldn't be the case if that's true.

**Comment by danawillow** [comment]
Changed my mind; not a bug since in the API, locationId is always a zone but you have to specify a region on create.

Let's say I specify us-central1 at the provider level and us-west1-b (but no explicit region) at the instance level. Should the instance create in us-west1 because I put that as my location id, or should it error because we took the region from the provider? The first one makes more sense just thinking about this resource individually, but the second makes more sense thinking about the provider as a whole and how we tend to fall back to getting the region from the provider when none is specified in a config.

**Comment by atmatthewat** [comment]
Possibly related to my #3690 - If you set the provider region to a zone (vs. unset as per this bug), you get even more confusing error messages
