### ISSUE TITLE
sql_database_instance doesn't have implicit dependency with private vpc connection when using private service access

### ISSUE THREAD

**Issue by kenzht** [terraform-providers/terraform-provider-google#3245]
when using private service access, resource google_sql_database_instance doesn't implicitly depend on private_vpc_connection and hence, requires explicitly defining depends on relationship with private_vpc_connection.
```
resource "google_sql_database_instance" "foobar" {
  depends_on = ["google_service_networking_connection.private_vpc_connection"]
```

**Comment by emilymye** [comment]
Unfortunately, this is true and pretty much unavoidable since we can't actually reference the networking connection in the SQL instance. As you can see in our [example for private ip instances](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance) we use a depends_on block. 

We certainly can improve the documentation around it but as of now we aren't able to do much else.
