### ISSUE TITLE
google_compute_vpn_tunnel doesn't support the Tag

### ISSUE THREAD

**Issue by kazuyatabata** [terraform-providers/terraform-provider-google#3246]
The resource google_compute_vpn_tunnel doesn't support the Tag.
It is published in the reference.
https://www.terraform.io/docs/providers/google/r/compute_vpn_tunnel.html#labels

# vpn_tunnnel.tf
```
resource "google_compute_vpn_tunnel" "tbt-vpn-tunnel1" {
  name          = "tbt-vpn-tunnel1"
…
  labels = {
      example = "tbt"
    }
```
# Error
```
Error: Error applying plan:

1 error(s) occurred:

* google_compute_vpn_tunnel.tbt-vpn-tunnel1: 1 error(s) occurred:

* google_compute_vpn_tunnel.tbt-vpn-tunnel1: Error updating VpnTunnel "tbt-vpn-tunnel1": googleapi: got HTTP response code 404 with body: Not Found
```

# Terraform Version
- Terraform v0.11.13
  - provider.google v2.1.0

# Affected Resource(s)
- google_compute_vpn_tunnel

**Comment by emilymye** [comment]
Thanks for submitting this issue. It turns out that currently the v1 compute API (GA Terraform Google provider) doesn't support labels for vpnTunnels but the beta API (and terraform-provider-google-beta) does support labels correctly now. If you need labels urgently, please use that provider to manage your vpnTunnels. Thank you!

**Comment by kazuyatabata** [comment]
Thank you for teaching me and fixing the reference https://github.com/terraform-providers/terraform-provider-google/pull/3277
