### ISSUE TITLE
Roadmap for V1

### ISSUE THREAD

**Issue by edward2a** [terraform-providers/terraform-provider-google#3248]
Hi everyone,

Just writing to ask what is the roadmap with provider V1 and whether there is a deprecation timeline.

This is due to provider V2 being available and apparently having more active development and I find myself writing / updating tf-gcp modules often, so I would like to plan ahead before putting any more effort on supporting V1 modules or migrate to V2.

Thank you.

**Comment by rileykarson** [comment]
Hey @edward2a!

The Terraform Provider release tooling only allows us to make releases linearly, so we're unable to make changes to `1.X` series of the provider (or even backport patches to anything but the latest release). As such, `2.X` is the only release series with active development, and we'd recommend making the migration at your earliest convenience.

Regardless of whether it was supported for providers or not, I'm unsure if we'd continue to backport changes- it's a conversation we haven't had yet, due to it being infeasible. Out of curiosity, do you see a large benefit to staying on a `1.X` series release?

**Comment by edward2a** [comment]
Thanks for the quick reply @rileykarson 

The question comes up as I am working on a project that is customising shared modules for specific organisation usage and have to decide whether to keep them as V1 or upgrade (many of the source modules from google are V1 code yet).

So I guess this actually resolves the issue altogether :+1:
