### ISSUE TITLE
Not able to create SQL db instance

### ISSUE THREAD

**Issue by selatamil** [terraform-providers/terraform-provider-google#3278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Affected Resource(s)

* google_sql_database_instance

### Terraform Configuration Files

resource "google_sql_database_instance" "default" {
  name                 = "dev-db-3"
  project              = "id"
  region               = "us-west1"
  database_version     = "MYSQL_5_7"

  settings {
    tier                        = "db-n1-standard-1"
    activation_policy           = "ALWAYS"
    disk_autoresize             = true
    ip_configuration {
            ipv4_enabled = "false"
            private_network = "https://www.googleapis.com/compute/v1/projects/id/global/networks/vpc-dev"
        }
    disk_size                   = "10"
    disk_type                   = "PD_SSD"
  }
}

When applying above code i'm getting below error 

1 error(s) occurred:

* google_sql_database_instance.default: 1 error(s) occurred:

* google_sql_database_instance.default: Error waiting for Create Instance:

In SQL console it's showing An unknown error occurred. Please help

**Comment by emilymye** [comment]
When I created it with your exact config and a random network on my project, it gave the same "Unknown error" (essentially server error from SQL). This is more likely a problem with your network or config than it is a Terraform issue. I also confirmed that removing your ip_configuration block results in a valid SQL instance, so I'd verify that your network is correctly created for [private IP](https://cloud.google.com/sql/docs/mysql/private-ip) usage. 

You can also confirm that other errors aren't showing up by running with `TF_LOG=DEBUG terraform apply`, but otherwise it would be hard to debug this internal error from our side.

**Comment by selatamil** [comment]
@emilymye  It helped, thank you for your quick solution!

**Comment by nccurry** [comment]
@selatamil What was the issue? I'm seeing a similar problem with a similar configuration.
