### ISSUE TITLE
google_container_cluster cluster_autoscaling feature is GA and is not "autoprovisioning"

### ISSUE THREAD

**Issue by erkolson** [terraform-providers/terraform-provider-google#3303]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Any version

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "main" {
  ...
  enable_autoscaling = "true"
  ...
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

`cluster_autoscaling` feature is GA and should be available in the GA provider.  `autoprovisioning` should be a separate attribute and in the beta provider.

### Actual Behavior

The documentation says that the `cluster_autoscaling` attribute is a feature also known as `autoprovisioning` and that both are beta features, available in the beta provider:
https://www.terraform.io/docs/providers/google/r/container_cluster.html#cluster_autoscaling

They are in fact two separate features.

### Steps to Reproduce

n/a

### Important Factoids

n/a

### References

https://www.terraform.io/docs/providers/google/r/container_cluster.html#cluster_autoscaling
https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning

* #0000

**Comment by emilymye** [comment]
@erkolson sorry for the late reply! We can certainly make the docs more clear, since this is fairly confusing. Node auto-provisioning is an additional feature that is considered part of [cluster autoscaling](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-autoscaler). 

However, in the actual REST API, the GA cluster autoscaling is configured via node pools (which we have implemented in GA, see [`google_container_node_pool.autoscaling`](https://www.terraform.io/docs/providers/google/r/container_node_pool.html#autoscaling)). The beta node autoprovisioning feature is configured via a cluster field called `autoscaling` in the [beta API cluster](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters). See specifically the [ClusterAutoscaling](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.ClusterAutoscaling) subobject, which `autoscaling` expects. 

We generally try to model naming after the API and this feature was implemented in parts. I can both understand why they named this new feature cluster-autoscaling (it's a autoscaling feature that applied per-cluster, rather than per node-pool) and why this is so terribly confusing to name it that when there is an existing, encompassing cluster autoscaler feature. Apologies!
