### ISSUE TITLE
Add folder support for shared VPC projects

### ISSUE THREAD

**Issue by lawsontyler** [terraform-providers/terraform-provider-google#3395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Currently it is possible to use `folder_id` with `google_project` resources.  I'd like to be able to use that with `google_compute_shared_vpc_host_project` and `google_compute_shared_vpc_service_project` as well.

### New or Affected Resource(s)

* google_compute_shared_vpc_host_project
* google_compute_shared_vpc_service_project

### Potential Terraform Configuration

```tf
resource "google_folder" "host-folder" {
  display_name = "Host Project 1"
  parent     = "organizations/1234567"
}
resource "google_folder" "shared-folder" {
  display_name = "Shared Project 1"
  parent     = "organizations/1234567"
}

resource "google_compute_shared_vpc_host_project" "host-project" {
    project = "my-host-project"
    folder_id = "${google_folder.host-folder.id}"
}
resource "google_compute_shared_vpc_shared_project" "shared-project" {
    host_project = "my-host-project"
    service_project = "my-service-project"
    folder_id = "${google_folder.shared-folder.id}"
}

```

**Comment by emilymye** [comment]
Since `google_compute_shared_vpc_*_project` resources just call [enableXpnResource](https://cloud.google.com/compute/docs/reference/rest/v1/projects/enableXpnResource) on the given `project`/`host_project`, the folder hierarchy follows from the project used. 

Your config above would be invalid, since it is implying `projects/my-host-project` has both `folders/host-folder` and `folders/shared-folder` as a parent. 

If you need to force the the folders --> projects --> shared_vpc_*_project creation order, you could just use a explicit `depends_on` attribute or interpolate values from `google_project` resources.

**Comment by rileykarson** [comment]
Also, possibly related: https://github.com/terraform-providers/terraform-provider-google/issues/3370
