### ISSUE TITLE
google_compute_project_metadata_item destroys existing (unmanaged) data

### ISSUE THREAD

**Issue by ayohrling** [terraform-providers/terraform-provider-google#340]
### Affected Resource(s)
- google_compute_project_metadata_item

### Terraform Configuration Files
```hcl
resource "google_compute_project_metadata_item" "ssh_public_key" {
  key = "sshKeys"
  value = "${var.ssh_user}:${file(pathexpand("${path.root}/files/publickey.pub"))}"
}
```

### Expected Behavior
This should add/remove/manage a key for `ssh_user` in the GCE project metadata

### Actual Behavior
This adds the key for the `ssh_user` to GCE project metadata and destroys all other keys.

**Comment by selmanj** [comment]
I believe this is expected behavior, if I'm understanding the issue correctly. To restate, this issue is reporting that the other _ssh keys_ in the metadata value for `sshKeys` are being overwritten (and NOT that other project metadata keys that are not `sshKeys` are being overwritten). Please correct me if I'm wrong.

`google_compute_project_metadata_item` lets you manage a single key/value entry within project metadata without having to manage all the other items. However, the 'sshKeys' item itself manages an entire list of keys. It sounds like you want to manage a single ssh key without having to explicitly list all of them.

Is that summary accurate?

**Comment by selmanj** [comment]
(Note that GCP has a whitelist-only API for managing users in a much more direct fashion: https://cloud.google.com/compute/docs/access/user-accounts/ . Once this API is stabilized and at least in beta we can work on exposing it as a resource).

Closing for now. Please reopen if I misinterpreted anything above.
