### ISSUE TITLE
Lack of possibility to apply 'empty' google_folder_organization_policy

### ISSUE THREAD

**Issue by radkomateusz** [terraform-providers/terraform-provider-google#3607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.11.13
+ provider.google v2.6.0

### Affected Resource(s)
google_folder_organization_policy

I assume that also:
google_organization_policy,
google_project_organization_policy

### Terraform Configuration Files
```tf
resource "google_folder_organization_policy" "disableServiceAccountCreation" {
  folder = "${google_folder.folder.name}"
  constraint = "iam.disableServiceAccountCreation"
}
```

### Expected Behavior

When resource doesn't have any policy specified (any from _boolean_policy_, _list_policy_, _restore_policy_ was defined), during apply, terraform should override existing policy to achieve this situation in UI:
![image](https://user-images.githubusercontent.com/3711948/57512157-39056480-730b-11e9-9304-b1969d79cd99.png). 

Based on tests, setting _boolean_policy_, _list_policy_ is equivalent of _Customise_ option, and _restore_policy_ is _Google-managed default_. 

### Actual Behavior
When I want to apply changes, I get: 
```
* google_folder_organization_policy.disableServiceAccountCreation: 1 error(s) occurred:

* google_folder_organization_policy.disableServiceAccountCreation: googleapi: Error 400: Policy and Constraint must be of the same type:
Policy:
Policy{version=0, constraint=constraints/iam.disableServiceAccountCreation, etag=<ByteString@33502cfe size=0>, requireNoExistingPolicy=false, updateTime=null, policyType=NotSet{}}
Constraint:
Constraint{version=0, name=constraints/iam.disableServiceAccountCreation, displayName=Disable service account creation, description=BETA: This boolean constraint disables the creation of service accounts where this constraint is set to `True`. By default, service accounts can be created by users based on their Cloud IAM roles and permissions., constraintDefault=ALLOW, constraintType=BooleanConstraint{}}, badRequest
```

Also, in situation when _boolean_policy_ or  _list_policy_ was set previously in tf config, and then I remove it, during apply I get the same error. 

### Steps to Reproduce

1.  create _google_folder_organization_policy_ resource without specifying any policy (_boolean_policy_, _list_policy_, _restore_policy_)
1. `terraform apply`

or 

1. create _google_folder_organization_policy_ resource with some policy (_boolean_policy_, _list_policy_, _restore_policy_)
1. `terraform apply`
1.  remove policy from resource
1. `terraform apply`

* #0000

**Comment by chrisst** [comment]
We don't usually add a default block if the API doesn't have the equivalent default logic. In this case the UI only has a default because they have chosen to show that 1 of these options is required using a radio button. Terraform doesn't currently have the ability to provide the same functionality.

Setting a default to look like the UI is problematic because there is only a single version of the UI and thus it could change the default at any time to something else. The terraform defaults are not dynamic and are set in stone once a version has shipped. If the default in the UI changes then all versions of the terraform google provider released before that change would forever have the "wrong" default.

I think the right fix here is to document the requirement better or reject a config at validation time.

**Comment by radkomateusz** [comment]
@chrisst Thanks for explanation. 

I was surprised, because I was able to successfully import that "UI default" policy into my terraform state, when resource hadn't set any policy block, and then _terraform plan_ said that everything is up to date. 

So, looking at your proposed changes, you want to enforce users to always use some policy in mentioned resources, am I right? (I see that for now it is only change in documentation). 
If it will be added to config validation, does it mean that user won't be able to specified that he wants policy to be not set? 
I want to enforce that given folder will have empty policy and in current behaviour at least _terraform plan_ shows that sth need to be changed (although without possibility to _apply_ changes via terraform). 

After proposed changes, the only way to achieve "empty" policy on given resource via terraform is to remove resource in tf config, am I right? But in that situation, could we still said that this resource is managed by terraform?

**Comment by chrisst** [comment]
After some more looking I'm not going to turn on validation to enforce the oneOf behavior on the Terraform side because you are right it is a valid API response to have no policy defined. The documentation update is still correct that you are unable to use them in combination with each other. In the rest docs it does clarify this:
> // Union field policy_type can be only one of the following:
  "listPolicy": {
    object(ListPolicy)
  },
  "booleanPolicy": {
    object(BooleanPolicy)
  },
  "restoreDefault": {
    object(RestoreDefault)
  }
  // End of list of possible types for union field policy_type.

I think I misunderstood this issue originally but I think you are wanting to go back to a default behavior after having added a policy at one point via Terraform. If this is the case then you should be using the [Restore Policy](https://cloud.google.com/resource-manager/reference/rest/v1/Policy#restoredefault). It should allow you to "undo" the policy changes you have made. If that is what you are looking for I can also update the docs to be a bit more clear on that. If I'm still not understanding the issue please let me know.

**Comment by radkomateusz** [comment]
Partially yes, I want to go back to a default behaviour after having added a policy at one point (via terraform or set manually). But by default behaviour, I understand the state where no policy is defined = _Inherit from parent's policy_. If I use _restore_policy_ mentioned by you, it will set _google-managed default_.
In situation when google-managed default is _allow_, and parent policy is _deny_, then setting google-managed default will override parent policy. That's not what I want. 

Currently only removing terraform resource would apply that change (restoring to no policy defined). Creating policy resource, importing it to tf state, removing it from tf config and applied changes and then recreating empty policy resource and importing it again is some kind of workaround, but it's tricky.

**Comment by chrisst** [comment]
Ok, I'm on the same page finally :) It would be nice if the API would allow us to get to that state with a standard update however I think the only way to achieve that state is by sending a DELETE to that constraint. I'll play around with a fix and see if I can find something reasonable.

**Comment by chrisst** [comment]
PR updated with a fix. It will allow you to specify none of the policies and revert to a default behavior.

**Comment by radkomateusz** [comment]
Thank you! That's exactly what I want to have. I hope that would be merged in the nearest future.
