### ISSUE TITLE
google_project_iam_member and google_project_iam_binding on same role

### ISSUE THREAD

**Issue by cristifalcas** [terraform-providers/terraform-provider-google#3621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
$ terraform -v
Terraform v0.11.13
+ provider.google v1.20.0
+ provider.kubernetes v1.6.2
+ provider.random v2.1.2
```
### Affected Resource(s)

* google_project_iam_member and google_project_iam_binding 

### Terraform Configuration Files

```tf

resource "google_project_iam_binding" "billing_project_manager" {
  project = "${var.project}"
  role    = "roles/billing.projectManager"

  members = [
    "user:user1@company.com",
  ]
}

resource "google_project_iam_member" "test-cfalcas" {
  project = "${var.project}"
  role    = "roles/billing.projectManager"
  member  = "user:user2@company.com"
}
```

### Expected Behavior

Only the binding should exist. Instead both users have access tot hat role

### Actual Behavior

Both users have access to the role.

Is this supported in version 1.x?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by emilymye** [comment]
This is probably happening only because the member is created after the binding is created.  `_iam_binding` resource will set the binding exactly for a given role, but `_iam_member` resource can only add members to a role's binding - this is intended behavior so users can prevent accidently writing over members not managed in Terraform. 

However, because we can't guarantee on our end that these two resources always run in this order and this will always create a perma-diff on subsequent applies (either to set the binding to exactly what was given, or to add the member), we generally do suggest not using these together (as stated in our [docs](https://www.terraform.io/docs/providers/google/r/google_project_iam.html)). I suggest just removing the member resource from your config and it should work as intended.
