### ISSUE TITLE
Dependency challenge with google_access_context_manager_service_perimeters

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#3630]
Hi,

I've got a challenge with managing google_access_context_manager_service_perimeters resources.

I've got some projects that belong to a regular perimeter and a bridge. The Google API seems to enforce some dependency, before a project can be added to a bridge it needs to be in one regular perimeter. I can get that to work with terraform by letting the bridge perimeter depend on the regular perimeter. Adding projects to a regular perimeter and bridge can be done in one terraform run.

However, when I want to remove a project, I run into issues because it first tries to delete it from the regular bridge, which fails because there is still a reference in the bridge perimeter: 

> Error 400: A project is in a Service Perimeter Bridge but no regular Service Perimeter. Each project in a Service Perimeter Bridge must be in a regular Service Perimeter.

I need to run terraform another time after this error and it will remove the project from the regular perimeter as well.

Are there any terraform tricks available to make this work without a second run?

Thanks for any help

Regards

Roland

**Comment by emilymye** [comment]
Can you give an example config/config change for your situation? I'm having a hard time understanding exactly what you are trying to do or what is happening since I'm not entirely familiar with AccessContextManager and it would help greatly. Are you saying that the deletion from the regular permitter fails the first time but not the second time?

**Comment by rolandkool** [comment]
Hi Emily,

Here's an example configuration. You'll need to substitute <id> with your access policy id and use some real project numbers.

```
resource "google_access_context_manager_service_perimeter" "dev" {
  parent         = "accessPolicies/<id>"
  name           = "accessPolicies/<id>/servicePerimeters/dev"
  title          = "dev"
  perimeter_type = "PERIMETER_TYPE_REGULAR"
  status {
    resources = [
      "projects/12345",
      "projects/67890",
    ] 
    restricted_services = [
      "bigquery.googleapis.com",
      "storage.googleapis.com",
      "pubsub.googleapis.com",
    ]
  }
}

resource "google_access_context_manager_service_perimeter" "dev_bridge" {
  parent         = "accessPolicies/<id>"
  name           = "accessPolicies/<id>/servicePerimeters/dev_bridge"
  title          = "dev_bridge"
  perimeter_type = "PERIMETER_TYPE_BRIDGE"
  status {
    resources = [
      "projects/12345",
      "projects/67890",
    ]
  }
  depends_on = ["google_access_context_manager_service_perimeter.dev"]
}
```

If you add a project to both the dev perimeter as well as the dev_bridge, it works in one run. If you remove that project from both, it will fail the first time.

Perimeters can contain lot's of projects so it possible you'll have both additions (new projects) and deletions (removed projects) at the same time when you want to keep this policy up to date.

Hope this clarifies it a bit more.

**Comment by emilymye** [comment]
Ah, I see. Unfortunately I just don't think it's possible in Terraform. There's not way to explicitly add depencies for updates unless unless the field being updated (i.e. project) is being interpolated into the bridge from the "regular" perimeter, and it would have to be an output only field on the perimeter. 

I don't know if we can actually do anything about this otherwise on the provider level. We can only ensure they don't run at the same time, and that's about it for controlling order of resource running. The solution might just need to be apply twice or ask Terraform core for help :/

**Comment by emilymye** [comment]
Going to close this out but please let me know if you have any other questions!
