### ISSUE TITLE
google_compute_zones requires project field, but not in the documentation

### ISSUE THREAD

**Issue by smaslennikov** [terraform-providers/terraform-provider-google#3634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.11.13
+ provider.google v2.6.0
+ provider.google-beta v2.6.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* `google_compute_zones`

### Terraform Configuration Files

```tf
provider "google" {}
data "google_compute_zones" "available" {}
```

### Debug Output

`* data.google_compute_zones.available: data.google_compute_zones.available: project: required field is not set`

### Expected Behavior

The data structure should be created.

### Actual Behavior

Data structure requires `project` field even though the [docs](https://www.terraform.io/docs/providers/google/d/google_compute_zones.html) say otherwise: "project (Optional) - Project from which to list available zones. Defaults to project declared in the provider."

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Is the field requirement stemming from the fact that it's not set in the provider (which, in my understanding would use my default project set in `gcloud`)?

**Comment by emilymye** [comment]
> Is the field requirement stemming from the fact that it's not set in the provider

Yep! Generally project is marked as optional on resources because you can omit it from the resource config specifically. That doesn't necessarily mean it's not a required field, it just doesn't need to be set in the resource specifically. From the docs for zone: "Project from which to list available zones. Defaults to project declared in the provider." The required field error is then actually returned from the provider-level check.

> (which, in my understanding would use my default project set in gcloud)?

Nope! We usually find project using the following order:
- project from resource
- provider-level project
- environment variables (see [provider docs](https://www.terraform.io/docs/providers/google/provider_reference.html#project-1))

I don't believe gcloud sets the project environment variable anymore.

**Comment by emilymye** [comment]
Based on the issue you just marked, users would either provide the project via a variable or when they initialize their providers.

**Comment by smaslennikov** [comment]
@emilymye cool, I'm able to run above code with proper environment variables set, as follows:

```
GOOGLE_REGION=us-central1 \
GOOGLE_PROJECT=myproject \
terraform apply
```

That explains everything, thank you!
