### ISSUE TITLE
Handle new Google Cloud Storage endpoints before 2019/06/20

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#3661]
GCS sent out a notice that they're introducing a second API endpoint on June 20th; as-is, we use full URLs in most storage resources, so users might be affected if they've provided references to buckets by the old URL and existing resources change their self links.

> If your code checks that the ‘selfLink’ field in bucket or object metadata points to www.googleapis.com, you will need to modify that check to allow either storage.googleapis.com or www.googleapis.com.

This is partly mitigated by the fact that Terraform configs containing both the bucket and child (eg: acl, object) should update simultaneously and see no diff, but configs where the `bucket` value is a self link added out of band (added by hand, or from a remote state for example) will be affected.

---

We should update GCS resources to handle references by partial URI (`/projects/{{project}}/RESOURCES/...`) soon, so that there are a couple provider releases by then.

**Comment by danawillow** [comment]
Storage resources all take the bucket name API-side rather than the full path, so trying to interpolate based on bucket or object self links already will result in errors (as far as I can tell from the API docs). Since all our documentation says to use names anyway I don't think we need to do anything here.
