### ISSUE TITLE
Feature request: support for logging sinks

### ISSUE THREAD

**Issue by rlisewski** [terraform-providers/terraform-provider-google#368]
Hi,
I'm trying to get notifications triggered by activity logs to Slack. The step after creating pub/sub topic is to create logging sink which exports logs to that topic. It can't be done via terraform. Here is related API
https://developers.google.com/apis-explorer/#search/logging.projects.sinks.create/

### Terraform Version
0.10.2

### Expected Behavior
Ability to create logging sinks

### Actual Behavior
Can't create logging sinks

**Comment by danawillow** [comment]
Project sinks fixed in #432, billing acct sinks in progress in #457

**Comment by daaain** [comment]
It seems that this feature should be ready in `master` as both PRs are now merged?

Apologies for the off topic question, but is there a way to use this somehow before 1.0 lands? I couldn't find anything in the docs about installing provider plugins from Github `master`. Or do you have any timelines yet when would this be released?

**Comment by danawillow** [comment]
There are two more stackdriver logging sinks (organizations and folders), so let's keep this open to track those.

You can build from source by cloning the repo and running `make build`- the next `terraform init` should pick that up (you may need to fiddle with your $PATH or other things). However, I strongly recommend against doing this for production resources- we make no guarantees that everything in a given release candidate won't change in backwards-incompatible ways before we actually make the release, so it's definitely a risky maneuver. We're hoping to do the release today, but since things can easily go wrong let's say within the next week.

**Comment by selmanj** [comment]
Release has occurred; you should be able to use the new project logging sink:

https://www.terraform.io/docs/providers/google/r/logging_project_sink.html
