### ISSUE TITLE
guest_accelerator with count of 0 forces node pool recreation (permadiff)

### ISSUE THREAD

**Issue by morgante** [terraform-providers/terraform-provider-google#3786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.13

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/cluster_regional.tf#L142

### Steps to Reproduce

1. Create a node pool without a guest_accelerator block that has count 0.
2. Observe the permadiff:

```
      node_config.0.guest_accelerator.#:                      "0" => "1" (forces new resource)
      node_config.0.guest_accelerator.0.count:                "" => "0" (forces new resource)
```

A guest_accelerator block with a count of 0 should be interpreted the same as a non-existent guest_accelerator block (and certainly not force a node pool recreation).

### References

* https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/120

**Comment by chrisst** [comment]
I'm testing out a fix for this, but I wanted to make sure you were also aware that you can also remove the `guest_accelerator` block using the empty list syntax. eg: `guest_accelerator = []`.

This is because we have marked `guest_accelerator` as an ["attribute as block"](https://www.terraform.io/docs/configuration/attr-as-blocks.html). Anything identified as this in the docs will accept the empty list syntax to remove the whole block since omitting the block will assume that it is a computed value.
