### ISSUE TITLE
Big Table - Recreates itself when node cluster # is different

### ISSUE THREAD

**Issue by michyliao** [terraform-providers/terraform-provider-google#4006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

0.11.

### Affected Resource(s)

google_bigtable_instance

### Terraform Configuration Files

resource "google_bigtable_instance" "dev_cluster" {
  project      = "${var.project}"
  name         = "${var.name}"
  cluster {
    cluster_id   = "${var.name}-cluster"
    zone         = "${var.region}"
    num_nodes    = "${var.cluster_size}"
    storage_type  = "SSD"
  }
  instance_type = "PRODUCTION"
}

### Expected Behavior

Big Table not to be recreated 

### Actual Behavior

Big table was recreated - data was destroyed and purged but previous monitoring stats are still there

### Steps to Reproduce

terraform apply

1. `terraform apply`

### References

Hi there,

While we were deploying changes for a different module (permissions), there was a change in our big table where the nodes went from 3 to 12. We had ran plan prior to our apply, but there was no state changes in our plan for bigtable. But while terraform apply was running, there was a pipeline that had trigger the cluster to go up to 12. This had cause a change in our bigtable state and destroyed and recreated our bigtable instance. This behaviour is something that we do not want, since all that was changed was the number of nodes in the cluster. 

Is this what is expected? or is this a bug - or can there be a flag set so that we prevent bigtable instances to be destroyed and purged when there is a diff with bigtable nodes. 

Thank you!

**Comment by rileykarson** [comment]
Hey @michyliao! That's definitely not expected behaviour from Terraform.

We don't currently support updating `num_nodes` (that's being tracked in https://github.com/terraform-providers/terraform-provider-google/issues/2521) and Terraform *will* attempt a recreation of the instance if a cluster has it's `num_nodes` value changed.

Terraform should never take action without indicating that it will in plan, and it won't modify it's intended actions even if resources managed by Terraform are modified out-of-band mid-apply. In short- if Terraform `plan` didn't indicate a recreation, that should not have happened.

Can you confirm on your `terraform apply` run that the `terraform plan` you supplied / the implicit confirmation plan if you didn't supply one had no changes planned on your bigtable instance?

**Comment by michyliao** [comment]
Hi Riley,

When we push our terraform apply in our pipeline, we enable -auto-approve since this is part of our CI/DI pipeline since we trigger terraform plan prior. So we just got unlucky in that split second.

> Edit: Terraform also won't ever try to recreate a bigtable instance based on a change in the number of nodes. That value isn't read back from the API, so unless a config value changed a recreation shouldn't be triggered.

There wasn't any config value change - other than our nodes `num_nodes = "${var.cluster_size}"` being set to 3. But when it was applied - the bigtable instance was at 12 nodes during a run. - so it did recreate was triggered in our scenario.

**Comment by rileykarson** [comment]
I checked again and I'd misread previously, we do read out of band changes to the number of nodes. My apologies for the confusion! You're right, this was likely unfortunate timing where Terraform hasn't seen a difference at plan time but did at apply time.

Unfortunately, when running with `-auto-approve`, changes like this will continue to be a risk. If you're able to, I'd strongly recommend using the [`-out` argument](https://www.terraform.io/docs/commands/plan.html#out-path) for `plan` to store your execution plan artifact, and to apply it by providing it as an parameter in `apply` instead of `-auto-approve`. This approach is highlighted in HashiCorp's Running Terraform in Automation guide's [automated workflow overview section](https://learn.hashicorp.com/terraform/development/running-terraform-in-automation#automated-workflow-overview).

**Comment by michyliao** [comment]
Ah okay!! Thanks for the headups and pointers @rileykarson .
