### ISSUE TITLE
google_compute_vpn_tunnel encrypted shared_secret

### ISSUE THREAD

**Issue by onetwopunch** [terraform-providers/terraform-provider-google#4012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current implementation of the `google_compute_vpn_tunnel` forces users to add a plain text shared secret in such a way that will always store this value in plain text in terraform state. Since it is not a dynamically generated secret, you also cannot use the `pgp_key` pattern elsewhere. My recommendation would be twofold:
1. Allow this shared secret to be dynamically generated and exported
2. Add the `pgp_key` attribute to allow encryption of this value as is common practice elsewhere in terraform such as [`aws_iam_access_key`](https://www.terraform.io/docs/providers/aws/r/iam_access_key.html)

### New or Affected Resource(s)

* `google_compute_vpn_tunnel`

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
resource "google_compute_vpn_tunnel" "tunnel1" {
  provider = "google-beta"
  name          = "tunnel1"
  peer_ip       = "15.0.0.120"
  pgp_key      = "keybase:username" # or GPG public key
  # Should not be required
  # shared_secret = "a secret message"

  target_vpn_gateway = "${google_compute_vpn_gateway.target_gateway.self_link}"
}

```

**Comment by paddycarver** [comment]
Hey @onetwopunch!

Sorry for the delay on this. I think we've talked about it a bit more over email, so I'm going to just try and briefly surface some of the rationale here in the interest of making it public. Also, I know I owe you a reply to your most recent email, sorry about that.

Basically, we've stopped using the pgp_key strategy, and as noted in #4325, we're looking to drop it entirely from the codebase in 3.0.0. This is the stance taken by pretty much all the HashiCorp-maintained or co-maintained providers at this point. The crux of the issue is that this was an experiment we don't feel was successful, and it was intended to solve a problem in a different context.

Originally, we started using pgp_key, I believe, in response to the concern that we were storing secrets in cleartext on disk. pgp_key was meant as an experiment in how to get around that. We've since introduced remote state backends with encryption, and stopped writing terraform.tfstate to disk when they're used, so that context no longer makes sense.

Fundamentally, there are a few problems that make pgp_key undesirable as a solution:

* PGP keys have no standard and consistent way of formatting them, as far as I know. Parsing them in a standard way is deceptively difficult.
* Once we encrypt the value, Terraform core is unable to detect that a value is encrypted, and so can't return a sensible/usable error about not having access to the key in question; instead, it shows a nonsensical diff, or loses the ability to track changes made outside Terraform.
* The use cases for using pgp_key are varied, and vary widely in how good an idea it is to use pgp_key for that. Some people use it for managing secrets in state, some people use it for managing access to secrets, and it's unclear what it's for right now.
* The use of pgp_key basically disables any interpolation functionality, which makes it a difficult solution to accept.

There's a more in-depth conversation about the inner workings of Terraform and its expectations and how pgp_key fits into them, and about the whackamole nature of the pgp_key solution and how unsustainable that is, but those four reasons are kind of the big ones. (That I can think of right now, more may occur to me later and I'll add them here if that happens.)

The future of that is still being decided, and a Terraform Core product manager will definitely have more to say there (with your permission, I'll intro you). But for the time being, we've decided against pgp_key.

That being said, an issue you raise here that I see is that you have to store the secret in a plaintext config file, which is not ideal. I'd support a "generate_shared_secret" field or something that would allow you to toggle the behavior of generating a random shared secret that wouldn't be stored in your config. In theory, you could achieve this with the `random` provider, though?

**Comment by onetwopunch** [comment]
I agree, under the limitations you describe, the only way of keeping that shared secret outside of terraform state without using a `null_resource` block would be to use the `random` provider. Thank  you for that in depth description.
