### ISSUE TITLE
Add the 'network' field to google_compute_address

### ISSUE THREAD

**Issue by spew** [terraform-providers/terraform-provider-google#4166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The network field is described in the official documentation as follows

network | stringThe URL of the network in which to reserve the address. This field can only be used with INTERNAL type with the VPC_PEERING purpose.

https://cloud.google.com/compute/docs/reference/rest/v1/addresses/get

### New or Affected Resource(s)

* google_compute_address

**Comment by megan07** [comment]
Hi @spew !

Thank you for opening this issue.  The `network` field is only a valid option on global addresses and is already an option on `google_compute_global_address`.  I have a side note on this PR if you’re interested in the errors I came across while testing the `purpose` field.

Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.  Thanks!
