### ISSUE TITLE
plan does not pick up change to google_service_account resource

### ISSUE THREAD

**Issue by leg100** [terraform-providers/terraform-provider-google#4170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.11.14
+ provider.external v1.2.0
+ provider.google v2.8.0
+ provider.google-beta v2.8.0
+ provider.local v1.3.0
+ provider.random v2.1.0
+ provider.template v2.1.2
+ provider.tls v2.0.1

### Affected Resource(s)

* google_service_account

### Terraform Configuration Files

```tf
@@ -1,5 +1,5 @@
 provider "google" {
   version = "~> 2.0"
-  project = "old"
+  project = "new"
   region  = "${var.region}"
 }

resource "google_service_account" "vault-admin" {
  account_id   = "${var.service_account_name}"
  display_name = "Vault Admin"
  depends_on = ["google_project_service.service"]
}
```

### Expected Behavior

I'd expect a plan to show a destroy/create of the resource.

### Actual Behavior

No change.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It's only when the resource is implicitly picking up the project from the provider that this bug appears. If the project was explictly passed as a resource argument and there was a change to that project, then a plan correctly picks up a change.

### References

* #0000

**Comment by rileykarson** [comment]
This is working as expected/intended. Resources store their project in state if the default provider project is used. Terraform has no mechanism to perform diffs like this.

**Comment by Daviey** [comment]
@rileykarson What do you mean "Terraform has no mechanism to perform diffs like this"?

This issue is about deploying a resource which inherits the project from the context, then changing the default project and terraform detecting the change for any resources, which should be a different project and therefore destroy/create the resource with the new project.

I think every other resource type does this, why shouldn't google_service_account resource?

For a real example where this bites, check out: https://github.com/terraform-google-modules/terraform-google-vault/issues/55

**Comment by rileykarson** [comment]
When the `project` value isn't defined explicitly in config, Terraform will have no `project` value in state. Google provider resources will infer the project from the provider in that case.

`project` across the provider is marked as an "complex default" value, where a user can set it in config or it can be inferred from elsewhere and recorded in state during a refresh. So once the resource has been created, the `project` value used will be recorded in state. To the provider, its indistinguishable whether the value recorded in state came from config or a refresh.

Because of that, we're unable to update the project to a new default value based on the project configured in the provider. Terraform isn't able to perform diffs based on values that are inferred like this.
