### ISSUE TITLE
google_compute_instance_template - define additional disks to be created and attached

### ISSUE THREAD

**Issue by timurshevekhman** [terraform-providers/terraform-provider-google#426]
Allow Terraform to support functionality available via API:
https://googlecloudplatform.uservoice.com/forums/302595-compute-engine/suggestions/8518333-instance-templates-define-additional-disk-to-be

Right now, if I want to use an instance group that creates a VM with multiple disks, I can't do that in Terraform. I have to use a startup script that creates and attaches a disk to a VM created in an instance group from an instance template.

**Comment by danawillow** [comment]
Just coming back to this- I'm not totally sure what this issue is about, since you can define multiple disks in an instance template. See the docs at https://www.terraform.io/docs/providers/google/r/compute_instance_template.html.

I'm going to go ahead and close this since I don't think there's anything that needs to be done here, but feel free to comment on this to reopen it if I'm misunderstanding.

**Comment by TinLe** [comment]
GCP driver v1.20
TF v0.11.11

I want to create  N disks, 1 per instance to be created in the template.  Then each instance will get a disk attached.   It seem I can not do that in current compute_instance_template.

`// Persistent disk for webservers
 resource "google_compute_disk" "web_data" {
     name = "${var.web_name}-data-${count.index}"
     count = "${var.web_count}"
     type = "pd-standard"
     size = "100"
     zone = "${var.zone}"
     labels {
         environment = "poc"
     }
 }
 //****************************************************************
 resource "google_compute_region_instance_group_manager" "web" {
   name               = "webserver"
   instance_template  = "${google_compute_instance_template.webserver.self_link}"
   base_instance_name = "webserver"
   region             = "${var.region}"
   target_size        = "${var.web_count}"
 }
 //****************************************************************
 resource "google_compute_instance_template" "webserver" {
   name_prefix    = "webserver-template-"
   machine_type   = "${var.web_machine_type}"
   can_ip_forward = false

   network_interface {
     subnetwork = "default"
   }

   labels = {
     environment = "poc"
   }

   scheduling {
     automatic_restart   = true
     on_host_maintenance = "MIGRATE"
   }

   disk {
     source_image = "${var.web_image}"
     auto_delete  = true
     boot         = true
   }

   disk {
     # source      = "${var.web_name}-data-${count.index}"
     source_image = "${google_compute_disk.web_data.self_link}"
     device_name = "disk-1"
   }

   metadata_startup_script = "${file("${path.module}/scripts/setup-web.sh")}"
 }
`

Running terraform plan with *source_image* will give me following error:

`terraform plan -var-file=poc.tfvars -target=module.web
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

google_compute_firewall.default: Refreshing state... (ID: web-firewall)
google_compute_disk.web_data[0]: Refreshing state... (ID: web-data-0)
google_compute_disk.web_data[2]: Refreshing state... (ID: web-data-2)
google_compute_disk.web_data[1]: Refreshing state... (ID: web-data-1)
google_compute_disk.web_data[3]: Refreshing state... (ID: web-data-3)
google_compute_disk.web_data[4]: Refreshing state... (ID: web-data-4)
google_compute_instance_template.webserver: Refreshing state... (ID: webserver-template-20190213234132371400000001)

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.web.google_compute_instance_template.webserver: 1 error(s) occurred:

* module.web.google_compute_instance_template.webserver: Resource 'google_compute_disk.web_data' not found for variable 'google_compute_disk.web_data.self_link'`

Switch to using *source* instead of *source_image* will work fine with plan, but failed when apply.
