### ISSUE TITLE
Refactor the google_dns_managed_zone to accept a map

### ISSUE THREAD

**Issue by flapp** [terraform-providers/terraform-provider-google#4308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description
Currently I'm trying to make a generic module that wraps around the  google_dns_managed_zone resource. 
One of the things I'm trying to do is make it accept an arbitrary amount of target nameservers and networks. 
But because of the way the resource is designed, with block based attributes instead of accepting a map, I'm unable to use a 'dynamic' resource. 

### New or Affected Resource(s)

* google_dns_managed_zone

### Potential Terraform Configuration
As an example, the resource accepts configuration like this: 
```
resource "google_dns_managed_zone" "private-zone" {
...
 private_visibility_config {
       networks {
         network_url =  "${google_compute_network.network-1.self_link}"
       }
       networks {
         network_url =  "${google_compute_network.network-2.self_link}"
       }
     }
...
}
```

What I would like to achieve is something like this: 

```
resource "google_dns_managed_zone" "private-zone" {
...
 private_visibility_config {
  dynamic "networks" {
    for_each = var.my_list
    content {
      network_url = "networks.value"
    }
  }
...
}
```

```tf

```
Essentially accepting a map, instead of a nested block would already do the trick.

### References
https://www.terraform.io/docs/providers/google/r/dns_managed_zone.html
https://www.terraform.io/docs/configuration/expressions.html

**Comment by danawillow** [comment]
Hi @flapp, sorry for the delay in responding! Nested blocks are actually the big use case for dynamic expressions, so this should be working as-is. I noticed that your example has quotes around "networks.value", whereas the docs at https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks show no quotes there. Changing that should be enough to get this working.

I'm going to go ahead and close this since I think this requires no provider-side changes, but if you're still having issues please feel free to open a new issue and fill out the bug template, and someone on our side will take a look.
