### ISSUE TITLE
Cloud Run: default values for location (region) and namespace

### ISSUE THREAD

**Issue by mikhailshilkov** [terraform-providers/terraform-provider-google#4334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current implementation of Cloud Run Service has `location` and `namespace` as required parameters. My suggestions:

- As `location` is basically a region to deploy to, why not name it `region` instead to keep it consistent with most other resources?
- `location` (`region`) should not be required and should use the region assigned to the provider.
- `namespace` should not be required and should use the project assigned to the provider.

### New or Affected Resource(s)

* google_cloud_run_service

### Potential Terraform Configuration

```tf
resource "google_cloud_run_service" "default" {
  name     = "tftest-cloudrun"
  provider = "google-beta"

  spec {
    containers {
      image = "gcr.io/cloudrun/hello"
    }
  }
}
```

### References

* [#3421](https://github.com/terraform-providers/terraform-provider-google/issues/3421)

**Comment by chrisst** [comment]
At this point even though namespace will not technically always be the project id/number I suspect that for managed cloudrun it is very unlikely to be something else. So I think it's ok to default to the project and I'll be adding this in the v1 release of the resource.

However for location there are only a few regions that managed cloudrun is available in and it has to be injected into the [domain of the cloudrun api](https://cloud.google.com/run/docs/reference/rest/#rest_endpoints) at run time which will require some custom shimming. Sourcing from multiple locations will make it more fragile and failure messages when it's missing or wrong will be confusing because requests will be sent to domain that doesn't exist. So for these reasons I am going to keep it as an explicit field on the resource.
