### ISSUE TITLE
Dataproc Notebooks

### ISSUE THREAD

**Issue by alexcurtin** [terraform-providers/terraform-provider-google#4359]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

The current terraform-provider-google and terraform-provider-google-beta do not support the beta feature of ML Engine Notebooks. 

https://cloud.google.com/ml-engine/docs/notebooks/create-new and https://cloud.google.com/ml-engine/docs/notebooks/ for further information.

### New or Affected Resource(s)

* google_ml_engine_notebook or *google_dataproc_notebook

### Potential Terraform Configuration

```tf
resource "google_dataproc_notebook" "default" {
  name     = "instance-name"
  location = "us-west1"
  zone      = "us-west1-b"
  provider = "google-beta"

  machine_configuration {
    framework = "intel-optomized-base"
    machine_type = "n1-standard-8"
    gpu_type   = "nvidia-tesla-k80"
  }

  disk {
   type = "ssd"
   size = "100" # in gbs
  }
}
```

### References

https://cloud.google.com/ml-engine/docs/notebooks/create-new and https://cloud.google.com/ml-engine/docs/notebooks/

**Comment by kaihendry** [comment]
Is "dataproc" notebook the same as https://console.cloud.google.com/ai-platform/notebooks/instances?

Confused by **dataproc**. Thank you,

**Comment by preston-hf** [comment]
> Is "dataproc" notebook the same as https://console.cloud.google.com/ai-platform/notebooks/instances?
> 
> Confused by **dataproc**. Thank you,

Hey stranger! I think this may be something else. I created an issue for AI notebooks though. #5879

**Comment by danawillow** [comment]
According to https://cloud.google.com/dataproc/docs/tutorials/jupyter-notebook#create_a_cluster_and_install_the_jupyter_component, the only things necessary to create a notebook in a cluster are:
1. create your cluster and install the Jupyter and Anaconda components on the cluster's master node
2. enable the Component Gateway

1 is already doable via cluster_config.software_config.optional_components, which I just learned isn't documented. Whoops! Filed https://github.com/terraform-providers/terraform-provider-google/issues/5904 to fix that. In the meantime, a config like the following from our tests would be how you set it:
```
resource "google_dataproc_cluster" "with_opt_components" {
	name   = "dproc-cluster-test"
	region = "us-central1"

	cluster_config {
		software_config {
			optional_components = ["ANACONDA", "JUPYTER"]
		}
	}
}
```

2 isn't doable yet because component gateway is still in alpha. Even though it's a public alpha, we don't love adding alpha features because they can sometimes be difficult from a backwards compatibility perspective. https://github.com/terraform-providers/terraform-provider-google/issues/4128 is the tracking issue for that.

For AI notebooks, let's use https://github.com/terraform-providers/terraform-provider-google/issues/5879 as the canonical issue. Going to go ahead and close this now that there are issues filed separately for all the separate parts of this. Please go and subscribe to / +1 the ones that are important for your use cases! Thanks all!
