### ISSUE TITLE
google_project_services not able to enable api

### ISSUE THREAD

**Issue by sarab321** [terraform-providers/terraform-provider-google#4380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
v0.12.1

### Affected Resource(s)
resource "google_project_services" "project" {
  project = "XXX"
  services   = ["oslogin.googleapis.com","compute.googleapis.com","container.googleapis.com"]
}

* google_XXXXX

### Terraform Configuration Files

resource "google_project_services" "project" {
  project = "terraform-251319"
  services   = ["oslogin.googleapis.com","compute.googleapis.com","container.googleapis.com"]
}

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Debug Output

Error: Error authoritatively enabling Project XXX Services: googleapi: Error 403: Cloud Resource Manager API has not been used in project XXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

### Expected Behavior

It should enable API

### Actual Behavior

Not enabling API

### Steps to Reproduce

1. `terraform apply`

**Comment by emilymye** [comment]
I believe this error is actually saying the call to enable services (oslogin, compute, container) is failing because you haven't enabled Cloud Resource Manager service, which is the service used to manage Project resources, and thus we can't read the project to enable services on.

This may be because you are using `google_project_services` (note the plural) which sets the enabled services **authoritatively**, i.e. it will disable all services that aren't included in this list. You might consider using `google_project_service` instead, which just manages enabling/disabling one service (use foreach for a list of services).

**Comment by sarab321** [comment]
Thanks @emilymye for your response, i have followed what you said. so i have 2 question

1) Lets say i have to enable multiple API such as compute.googleapis.com and container.googleapis.com. How i can do it
2) Also, i have to enable cloud resource manager service, which i am doing manually. 

Can you tell the step where cloudresourcemanager, compute and container API can be enabled in single step

**Comment by jaceq** [comment]
I have a similar problem with container.googleapis.com and redis.googleapis.com... with TF sometimes I get a timeout, sometimes it says 'OK.... but then when I try to use them it says it's disabled...

**Comment by ndmckinley** [comment]
`google_project_services` is going to be removed in version 3.0.0 due to many people experiencing problems like this - we are recommending the use of https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/project_services#project-api-activation.  I'll close this since it is obsolete - refers to a resource we are removing.
