### ISSUE TITLE
Go Sum DB (go 1.13) requires changing the package path in go.mod

### ISSUE THREAD

**Issue by yukinying** [terraform-providers/terraform-provider-google#4398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

v0.11

### Affected Resource(s)

ALL.

### Terraform Configuration Files

Not in scope of this bug.

### Actual Behavior

To support older version of terraform (v0.11), validator needs to use terraform_provider_google v2.0.0. It used to be vendored in the project, but today I removed the vendor code and run go build in my project, it starts to complain about missing https://sum.golang.org/lookup/github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: 410 Gone

### Steps to Reproduce

I created a blank new repository to reproduce this problem:

```
$ go mod init github.com/yukinying/testing
go: creating new go.mod: module github.com/yukinying/testing

$ go get github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible
go: finding github.com v2.0.0+incompatible
go: finding github.com/terraform-providers v2.0.0+incompatible
verifying github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: reading https://sum.golang.org/lookup/github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: 410 Gone

$
```

### Important Factoids

None.

**Comment by yukinying** [comment]
I am using go with version go1.13rc1. I am still checking if that would have caused the problem.

**Comment by rileykarson** [comment]
@yukinying did you end up finding if that was the case?

**Comment by yukinying** [comment]
It does. If I use go runtime v12 there are not issue. Note that go runtime v13 is now a stable release (Sept 3rd).

**Comment by yukinying** [comment]
Step to reproduce: 
```
$ go version
go version go1.13rc1 linux/amd64

$ go mod init github.com/yukinying/testing
go: creating new go.mod: module github.com/yukinying/testing

$ go get github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible
go: finding github.com/terraform-providers v2.0.0+incompatible
go: finding github.com v2.0.0+incompatible
verifying github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: reading https://sum.golang.org/lookup/github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible: 410 Gone
```

**Comment by yukinying** [comment]
In constrast with go runtime v12: 
```
$ rm go.mod go.sum

$ ~/goruntime/go/bin/go version
go version go1.12.9 linux/amd64

$ ~/goruntime/go/bin/go mod init github.com/yukinying/testing
go: creating new go.mod: module github.com/yukinying/testing

$ ~/goruntime/go/bin/go get github.com/terraform-providers/terraform-provider-google@v2.0.0+incompatible
go: downloading github.com/hashicorp/terraform v0.11.9-0.20180926212128-35d82b055591
go: downloading google.golang.org/api v0.0.0-20181217000635-41dc4b66e69d
go: downloading golang.org/x/oauth2 v0.0.0-20181203162652-d668ce993890
go: extracting golang.org/x/oauth2 v0.0.0-20181203162652-d668ce993890
go: extracting github.com/hashicorp/terraform v0.11.9-0.20180926212128-35d82b055591
go: extracting google.golang.org/api v0.0.0-20181217000635-41dc4b66e69d
go: downloading github.com/mitchellh/go-homedir v1.0.0
go: downloading cloud.google.com/go v0.34.0
go: downloading golang.org/x/net v0.0.0-20190119204137-ed066c81e75e
go: downloading golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: downloading google.golang.org/grpc v1.17.0
go: downloading github.com/hashicorp/hcl2 v0.0.0-20181215005721-253da47fd604
go: downloading github.com/hashicorp/go-uuid v1.0.0
go: extracting github.com/mitchellh/go-homedir v1.0.0
go: extracting github.com/hashicorp/go-uuid v1.0.0
go: extracting github.com/hashicorp/hcl2 v0.0.0-20181215005721-253da47fd604
go: extracting google.golang.org/grpc v1.17.0
go: downloading github.com/zclconf/go-cty v0.0.0-20181218225846-4fe1e489ee06
go: downloading golang.org/x/sys v0.0.0-20190123074212-c6b37f3e9285
go: extracting golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: extracting github.com/zclconf/go-cty v0.0.0-20181218225846-4fe1e489ee06
go: downloading github.com/golang/protobuf v1.2.0
go: downloading github.com/hashicorp/go-getter v1.0.1
go: extracting golang.org/x/net v0.0.0-20190119204137-ed066c81e75e
go: extracting github.com/hashicorp/go-getter v1.0.1
go: downloading github.com/hashicorp/hil v0.0.0-20170627220502-fa9f258a9250
go: downloading google.golang.org/genproto v0.0.0-20181218023534-67d6565462c5
go: extracting github.com/hashicorp/hil v0.0.0-20170627220502-fa9f258a9250
go: extracting github.com/golang/protobuf v1.2.0
go: extracting golang.org/x/sys v0.0.0-20190123074212-c6b37f3e9285
go: extracting cloud.google.com/go v0.34.0
go: downloading go.opencensus.io v0.18.0
go: extracting go.opencensus.io v0.18.0
go: extracting google.golang.org/genproto v0.0.0-20181218023534-67d6565462c5
```

**Comment by rileykarson** [comment]
I believe [this line](https://github.com/terraform-providers/terraform-provider-google/blob/master/go.mod#L1) is supposed to contain a `/v2` suffix, and should have since `2.0.0`.

However, adding that suffix will effectively change the package of the provider from `github.com/terraform-providers/terraform-provider-google` to `github.com/terraform-providers/terraform-provider-google/v2`. While it seems necessary for Go 1.13rc1+ so far, this may? (it's unclear- it could be transparent) mean older versions of Go may not correctly handle the transition. It's [recommended that we cut a major release](https://github.com/golang/go/wiki/Modules#incrementing-the-major-version-when-first-adopting-modules-with-v2-packages) to "adopt" modules for a package >= `2.X`.

Since we're primarily a binary, and not a library, we're not going to cut a major release of the library just for Go Modules. Our versioning / release scheme is SemVer for the _binary_ and not the exported functions of this repo.

I'll bring this issue up with HC in the near future (HashiConf means they+I am fairly busy until EOW next week) to see if they've encountered it yet. The AWS provider seems to be in the same situtation.

**Comment by rileykarson** [comment]
Also, this seems to primarily be a requirement for the sum DB introduced in `1.13`. Can you test with `GOSUMDB=off` set?

**Comment by yukinying** [comment]
It works with `GOSUMDB=off`.

**Comment by rileykarson** [comment]
Great- retitling the issue to reflect that this is a restriction of that sum db. Is it a big problem for you / Validator to disable use of the sum db while importing this repo as a module?

I'm going to raise this with the team regardless- we should follow the module spec more closely here- but (with what I know right now) I'll feel a lot better about probably making the change as part of `3.0.0` instead of in the middle of the `2.X` series. That'll give us time to raise with HC and to make sure we make a decision that's in line with other providers.

**Comment by yukinying** [comment]
The GOSUMDB=off works for a short term mitigation. 

I like the idea of having a verifiable checksum audited but this may be my personal view. `v3.0.0` is definitely a good idea to make this happen.

**Comment by clebs** [comment]
I also found an easier fix, you can provide the **commit hash of the version you want to have** and go mod will automatically convert it into a [pseudo-version](https://tip.golang.org/cmd/go/#hdr-Pseudo_versions). That way it will not complain about V2.

For example, I added this line to `go.mod` require (hash corresponds to v2.4.1):
`github.com/terraform-providers/terraform-provider-google f9a9636be7cd4c04c336a68e85767f28ce1b1236`

It was converted into this pseudo-version by go mod:
`github.com/terraform-providers/terraform-provider-google v1.20.1-0.20190430222256-f9a9636be7cd`

In turn it found the last valid version before the given commit and added date and hash.
This way the checksum does not complain.

**Comment by paddycarver** [comment]
Hi! Unfortunately, depending on providers at the Go package level is not something that Terraform endorses or that HashiCorp is willing to support at this time. There's (now) [a page](https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html#do-not-import-providers-as-go-modules) on terraform.io laying out the reasoning behind this and the suggested alternative paths available, but the crux is that our providers are versioned to follow semver for the HCL interface, not the Go interface. Conflating those two interfaces into a single semver number is either difficult or impossible, so to avoid confusion we would rather discourage the import of providers as Go modules.

If there's a helper function or utility that you believe would be beneficial to the community to extract from the provider, I'd request an issue about that specific use case, and we can look into potentially extracting it as a standalone Go module that the provider imports.

If you're looking to drive the provider as Terraform would, I recommend interfacing with the protobuf API as Terraform does, rather than calling the Go methods directly.
