### ISSUE TITLE
Allow setting num_nodes for DEVELOPMENT clusters

### ISSUE THREAD

**Issue by Legogris** [terraform-providers/terraform-provider-google#4399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
```
Terraform v0.11.14
+ provider.google v2.8.0
```

### Affected Resource(s)

* google_bigtable_instance

We have previously been able to use the same module for prod and development and templating in values for number of nodes, type, etc, that differs between environments. As of #2401 / https://github.com/GoogleCloudPlatform/magic-modules/pull/679, we can no longer reuse templates in this way, so it is a breaking change for us (since we can't have fields optionally unset). I'd prefer being able to set num_nodes to 1 for development instances only.

Alternatively, make `instance_type` required to avoid the scenario motivating https://github.com/GoogleCloudPlatform/magic-modules/pull/679

**Comment by rileykarson** [comment]
Hey @Legogris!

You're correct that this was a breaking change- it was made as part of a major release, `2.0.0`. `num_nodes` not being able to be set for `DEVELOPMENT` instances improves the validation of the resource, so I'm not sure it's a change I'd like to revert either. Additionally, this is solved entirely by using Terraform 0.12 instead of Terraform 0.11, where conditionally setting fields is possible.

Setting `instance_type` to `Required` would be another breaking change, so that's not really feasible.
