### ISSUE TITLE
CSEK and other secrets should not be stored in terraform state

### ISSUE THREAD

**Issue by KbLev** [terraform-providers/terraform-provider-google#4514]
### Description

When deploying **google_compute_disk** resource with Customer-Supplied Encryption Key, this secret will be stored in the terraform state. Companies go through great lengths to secure this peace of information with hardware-based HSM, KMS encryption etc. and it shouldn't be remembered in the state (and other secrets in general, including contents of sensitive files).

There's not much benefit in keeping track of CSEK anyway because a change would just force a redeployment of the resource which is not the desired action in most cases.

It's not possible to secure the terraform state on the same level as a secret string, for example with Hardware-based HSM, due to the way how this is consumed by terraform.

### Affected Resources

* [google_compute_disk](https://www.terraform.io/docs/providers/google/r/compute_disk.html#sha256-1)
* [google_compute_instance.boot_disk](https://www.terraform.io/docs/providers/google/r/compute_instance.html#disk_encryption_key_raw)
* [google_compute_instance.attached_disk](https://www.terraform.io/docs/providers/google/r/compute_instance.html#disk_encryption_key_raw-1)

### Terraform State sample

The current behaviour the state file contains the CSEK in clear text under the **raw_key** property. 

```tf
resource "google_compute_disk" "data1" {
  name  = "csek-1-data1"
  type  = "pd-standard"
  zone  = "europe-west2-c"
  size  = "10"

  disk_encryption_key {
    raw_key = "${var.csek}"
  }  
}
```
```
terraform apply -var 'csek=HO1FpIVyJZc/Tpq39Kyann01eJsw4vA9jCjYq3tKDOU='
```

**State file:**

```json
    {
      "module": "module.vm1",
      "mode": "managed",
      "type": "google_compute_disk",
      "name": "data1",
      "provider": "provider.google",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "creation_timestamp": "2019-09-13T08:06:45.070-07:00",
            "description": "",
            "disk_encryption_key": [
              {
                "kms_key_self_link": "",
                "raw_key": "HO1FpIVyJZc/Tpq39Kyann01eJsw4vA9jCjYq3tKDOU=",
                "sha256": "UJeOcL0cJoetj3QCqVTNcO6o9oOXmDzO/J1Iz0v4SRA="
              }
            ],
            "disk_encryption_key_raw": null,
            "disk_encryption_key_sha256": null,
            "id": "csek-1-data1",
            "image": "",
            "label_fingerprint": "42WmSpB8rSM=",
            "labels": null,
            "last_attach_timestamp": "",
            "last_detach_timestamp": "",
            "name": "csek-1-data1",
            "physical_block_size_bytes": 4096,
            "project": "csek-vms",
            "self_link": "https://www.googleapis.com/compute/v1/projects/csek-vms/zones/europe-west2-c/disks/csek-1-data1",
            "size": 10,
            "snapshot": "",
            "source_image_encryption_key": [],
            "source_image_id": "",
            "source_snapshot_encryption_key": [],
            "source_snapshot_id": "",
            "timeouts": null,
            "type": "pd-standard",
            "users": [],
            "zone": "europe-west2-c"
          },
          "private": "eyJlMmJmYjczMC1lY2FhLTExZTYtOGY4OC0zNDM2M2JjN2M0YzAiOnsiY3JlYXRlIjozMDAwMDAwMDAwMDAsImRlbGV0ZSI6MjQwMDAwMDAwMDAwLCJ1cGRhdGUiOjI0MDAwMDAwMDAwMH19"
        }
      ]
    }
```

### References

* https://www.terraform.io/docs/state/sensitive-data.html

**Comment by paddycarver** [comment]
Hi there! In accordance with [Terraform's guidance](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state) on best practices for providers, we're not going to implement this. The suggested workaround is to use an [enhanced remote backend](https://www.terraform.io/docs/backends/types/index.html), which should meet most security needs.

The workaround of simply not storing the CSEK or other secrets in state is, unfortunately, not really something we can do with Terraform reasonably; not storing them means Terraform believes that they're changing on every apply, since it's diffing the config and the state. This would lead to a redeploy on every apply, which is undesirable.

If an enhanced remote backend can't solve this issue for someone's use case, the recommended path forward is to weigh in on the [upstream issue](https://github.com/hashicorp/terraform/issues/516) about this with your use case and requirements.
