### ISSUE TITLE
Google cloud...create mutiple vm using same manifest file.

### ISSUE THREAD

**Issue by vaibhavd87** [terraform-providers/terraform-provider-google#4636]
If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)
Hi,

I have very simple requirement. I want to use same manifest file mention below to create multiple VM’s. VM name should be user provided. Also able to destroy any particular VM, if required.

Terraform provider  Google

Code :

provider "google" {
  credentials = "${file("terraform-sa.json")}"
  project     = "utility-node-247607"
  region      = "us-central1"
  zone        = "us-central1-c"
}
resource "google_compute_instance" "default1" {  
  name         = "var.name1"
  machine_type = "f1-micro"

  boot_disk {
    initialize_params {
      image = "debian-cloud/debian-9"
    }
  }
  network_interface {
    network = "default"
  }
}

Thanks

**Comment by rileykarson** [comment]
It sounds like you'd be interested in Modules! https://www.terraform.io/docs/modules/index.html

With modules, you can define a shared configuration for a set of resources including a limited set of inputs (such as a name). You can re-use a module definition multiple times in order to control individual sets of resources.

Closing this out- this issue tracker isn't really for usage questions and is focused more on bugs/feature requests/project tracking. The resources linked in the issue template you used or on https://www.terraform.io/docs/providers/google/index.html will be more helpful.
