### ISSUE TITLE
Creating Shared VPC through terraform and launching VMs in it

### ISSUE THREAD

**Issue by Shriyut** [terraform-providers/terraform-provider-google#4961]
I've been trying to create a shared vpc through terraform but this is the error that I get

Error: googleapi: Error 403: Required 'resourcemanager.projects.get' permission for 'projects/project-2-256305', forbidden on main.tf line 8, in resource "google_compute_shared_vpc_service_project" "service1": 8: resource "google_compute_shared_vpc_service_project" "service1" {

I tried creating the VPC manually and then creating the VM in a VPC( in host project) from terraform scripts in service project. VMs need to be a part of service project with network interface of host project

network_interface {
    network = "host-vpc"
     subnetwork = "host-subnet-1"  
      subnetwork_project ="host-prj-249608" 
 access_config {
      // Ephemeral IP
    }
  }

Adding this block resulted in

Error: Error creating instance: googleapi: Error 403: Required 'compute.subnetworks.use' permission for 'projects/host-prj-249608/regions/asia-east1/subnetworks/host-subnet-1'More details:Reason: forbidden, Message: Required 'compute.subnetworks.use' permission for 'projects/host-prj-249608/regions/asia-east1/subnetworks/host-subnet-1'Reason: forbidden, Message: Required 'compute.subnetworks.useExternalIp' permission for 'projects/host-prj-249608/regions/asia-east1/subnetworks/host-subnet-1'

I added the permissions to the user that I was using as well as the service account.
But then I got this error.

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].network': 'projects/project-1-256305/global/networks/host-vpc'. The referenced network resource cannot be found., invalid

I'm way beyond confused as of now and I could really use any help.

**Comment by slevenick** [comment]
It looks like you are having permissions issues.

You are creating resources across two projects with a single service account via terraform, so that service account needs to have the necessary permissions on *both* projects. It looks like you added permissions on the service account for `host-prj-249608` to resolve the first 403 error, but I would guess that the service account does not have permissions on `project-1-256305`.

If you grant permissions on `project-1-256305` to the service account that terraform runs as, does it fix your problem?

**Comment by Shriyut** [comment]
Thanks @slevenick 
That did the trick
