### ISSUE TITLE
Shielded GKE cluster nodes

### ISSUE THREAD

**Issue by dlinares-linux** [terraform-providers/terraform-provider-google#4976]
Hi all,

Raising this as a question as I am not sure it's a bug or just my misunderstanding.
I am using "google-beta" providers (terraform-providers/google-beta) 3.0.0-beta.1 to deploy a GKE cluster with a separately managed node pool.
I have the following structure:

```
resource "google_container_cluster" "gke_cluster" {
  provider = "google-beta"
  ...
  enable_shielded_nodes = true
  ...
}

resource "google_container_node_pool" "gke_node_pool" {
  provider = "google-beta"
   ...
   node_config {
     ...
     shielded_instance_config {
       enable_secure_boot          = true
       enable_integrity_monitoring = true
     }
     ...
  }
  ...
}
```

I have then added an org policy to prevent at org level the creation of non-shielded compute instances : 
```
resource "google_organization_policy" "org_policy_compute_require_shielded_vm" {
  org_id     = var.org_id
  constraint = "compute.requireShieldedVm"

  boolean_policy {
    enforced = true
  }
}
```

With this configuration, I am getting the following error:

```
Instance 'gke-xxxxxxx' creation failed: Constraint constraints/compute.requireShieldedVm violated for project projects/zzzzzzzzz. Secure Boot is not enabled in the 'shielded_instance_config' field. See https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints for more information.
```

So I am wondering, first if the "enable_shielded_nodes" and "shielded_instance_config" are kind of redundant, and then, what would be the right config to use to properly have shielded nodes.

Kind regards,
David

**Comment by slevenick** [comment]
Hey @dlinares-linux 

What I think is happening here is that the `google_container_cluster` creates a default node pool when it is created. That default pool would be replaced later with the `google_container_node_pool` that you have declared, but the default pool defaults the secure boot flag to false, which fails and stops execution.

Could you try adding a similar `node_config` with `shielded_instance_config` to the `google_container_cluster`? Documentation can be found here: https://www.terraform.io/docs/providers/google/r/container_cluster.html#node_config

You may also need to ignore changes to that field:
```
resource "google_container_cluster" "gke_cluster" {
  ...
  lifecycle {
    ignore_changes = [
      node_config,
    ]
  }
}
```

If that doesn't work can you post debug logs for the failing run? They will contain information I can hopefully use to track down the issue

**Comment by dlinares-linux** [comment]
Hi @slevenick ,
Thanks a lot. Your suggestion worked and I needed the following to allow the creation of Shielded VMs with the org policy in place:

```
resource "google_container_cluster" "gke_cluster" {
  provider = "google-beta"
  remove_default_node_pool = true
  ...
  node_config {
    shielded_instance_config {
      enable_secure_boot          = true
      enable_integrity_monitoring = true
    }
  }

  lifecycle {
    ignore_changes = [
      node_config,
    ]
  }
  ...
}

resource "google_container_node_pool" "gke_node_pool" {
  provider = "google-beta"
   ...
   node_config {
     ...
     shielded_instance_config {
       enable_secure_boot          = true
       enable_integrity_monitoring = true
     }
     ...
  }
  ...
}
```

I have tested a few combinations with and without the flag `enable_shielded_nodes = true` in `google_container_cluster` but it seems this flag has no effect at all and we absolutely need both shielded_instance_config blocks.

**Comment by dlinares-linux** [comment]
Hi @slevenick ,
Happy for this issue to be closed.
Would you like me to raise a new one to get an understanding of the flag `enable_shielded_nodes`?
As mentioned above, that flag doesn't seem to have any effect at all.

**Comment by slevenick** [comment]
Frankly I'm not super sure what that flag does either. It seems like it *should* cause the default node pool to have shielded nodes, but I think it requires some extra configuration to make that work.

Following https://cloud.google.com/kubernetes-engine/docs/how-to/shielded-gke-nodes allows us to create a cluster with shielded nodes enabled via gcloud, and has this field set along with a couple others. But this may not work due to how terraform configures the initial cluster

**Comment by shane-lawrence** [comment]
There's a lot of misunderstanding around this set of features, and I think [the docs](https://cloud.google.com/kubernetes-engine/docs/how-to/shielded-gke-nodes) were somewhat confusing (though they've gradually improved over time). I believe there are actually three separate features that are all configured independently of each other. "Shielded" seems to be the name for the group of features, as well as one of the individual features within the group. The other two features within the group are labelled "optional" features, which is a bit misleading because all three features are optional.

#### 1. Shielded Nodes
`--enable-shielded-nodes`

**Scope**: This feature is only enabled at the cluster level. When this setting is enabled for the cluster, it applies to all nodes in the cluster and can't be overridden by any node pool setting. 

**Effect**: This changes the control plane to enable the [node provenance check](https://github.com/kubernetes/cloud-provider-gcp/blob/c8332db61a9c2334f52d8dfa44a35cb986befb17/cmd/gcp-controller-manager/csr_approver.go#L518), which only allows a node to join the cluster if it has a vTPM attestation that it's in the correct GCP project and physically located in a Google datacenter. 


#### 2. Secure Boot
`--shielded-secure-boot`

**Scope**: This feature is enabled at the node pool level, but it can be set at the cluster level to change the default setting for node pools in the cluster. Setting this on a node pool will override the cluster's default setting for this feature. 

**Effect**: All nodes in the node pool must verify the signature of all boot components at startup. Any boot component that isn't properly signed will not be allowed to run.

#### 3. Integrity Monitoring
`--shielded-integrity-monitoring`

**Scope**: This feature is enabled at the node pool level, but it can be set at the cluster level to change the default setting for node pools in the cluster. Setting this on a node pool will override the cluster's default setting for this feature. 

**Effect**: All nodes in the node pool will use Measured Boot to compare the boot sequence to a known-good policy and generate related Cloud Monitoring/Cloud Logging reports/events.
