### ISSUE TITLE
Error: no schema available for google_project_services.default while reading state

### ISSUE THREAD

**Issue by benbro** [terraform-providers/terraform-provider-google#4986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.16
+ provider.google v3.0.0-beta.1
+ provider.local v1.4.0

### Affected Resource(s)

google_project_services

### Terraform Configuration Files
I was using google_project_services with a previous plugin version.
```tf
resource "google_project_services" "default" {
 project = "${var.project_id}"
 services = [
   "compute.googleapis.com",
   "oslogin.googleapis.com",
   "storage-api.googleapis.com"
 ]
}
```
I've got a warning that it's deprecated and need to be replaced with google_project_service but got errors about compute.googleapis.com being used by resources.
```tf
resource "google_project_service" "service_compute" {
  project = var.project_id
  service = "compute.googleapis.com"
}

resource "google_project_service" "service_oslogin" {
  project = var.project_id
  service = "oslogin.googleapis.com"
}

resource "google_project_service" "service_storage" {
  project = var.project_id
  service = "storage-api.googleapis.com"
}
```

I've upgraded terraform and the google provider plugin with "terraform init --upgrade". I don't know why the google plugin automatically upgraded to a beta version instead of warning me. The 3.0 beta plugin doesn't understand google_project_services any more so know I'm stuck between versions.
Is there a workaround? Can I edit the remote tfstate and delete the resource manually?

```tf
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://www.hashicorp.com/security
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug) then please include both the
# version of the config before the change, and the version of the config after the change.
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ndmckinley** [comment]
I recommend you follow https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#i-accidentally-upgraded-to-3-0-0-how-do-i-downgrade-to-2-x-, then update your config to remove any deprecation warnings.

If this is a production configuration or otherwise needs to be stable, I recommend you use a version constraint - https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#provider-version-configuration - by default, terraform will upgrade you to the most recent version, without consideration for whether it's a beta or even a major version release.

To deal with remote state, you should be able to use `terraform state rm google_project_services.default` once you downgrade.  That plus `terraform refresh` should do it for you.

I'm closing this since I think the question is answered, but please comment and I'll be happy to help if you have any further issues or if this doesn't help you.
