### ISSUE TITLE
unexpected EOF error

### ISSUE THREAD

**Issue by TraGicCode** [terraform-providers/terraform-provider-google#513]
It seems after upgrading to v1.0.0 i am getting the following error

`* google_compute_instance.windows_node: unexpected EOF`

### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
Please list the resources as a list, for example:
- google_compute_instance

### References

#479

**Comment by paddycarver** [comment]
According to @TraGicCode, this was resolved once they updated to use `self_link` instead of `name` for their disk in `attached_disk`, as described in #514. I'm going to close this out, though the debug log we got suggests this may still be an issue. Unfortunately, we no longer have a working reproduction for it.

That said, if anyone else runs into this, it'd be awesome to let us know.
