### ISSUE TITLE
Add option to set TTL for the DNS records created by google_dns_managed_zone

### ISSUE THREAD

**Issue by natarajaya** [terraform-providers/terraform-provider-google#5280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Seems like currently there is no way to set TTL for the NS and SOA records created by `google_dns_managed_zone`. TTL is always set to default value (21600 seconds) for both records.

### New or Affected Resource(s)

* google_dns_managed_zone

### Potential Terraform Configuration

```tf
# Resource below will create 2 records (NS and SOA) in Cloud DNS.
# Currently resource configuration does not allow to set TTL for these records.

resource "google_dns_managed_zone" "root_zone" {
  name        = "${replace(var.organization_domain, ".", "-")}"
  dns_name    = "${var.organization_domain}."
  description = "root ${var.organization_domain} DNS zone"

  lifecycle {
    prevent_destroy = "true"
  }
}
```

**Comment by danawillow** [comment]
The ManagedZone API doesn't have a `ttl` attribute unfortunately, so this isn't a trivial change (https://cloud.google.com/dns/docs/reference/v1/managedZones). However, we do have the ability to change `ttl` on record sets that are managed by Terraform using the `ttl` attribute on [`google_dns_record_set`](https://www.terraform.io/docs/providers/google/r/dns_record_set.html). For this particular resource, the provider will override existing entries (rather than complaining that it already exists), so if you're willing to manage the NS and SOA records using Terraform, then you can add resources for them and it'll work. Does that work for your use case?

**Comment by natarajaya** [comment]
@danawillow Yes, to workaround this, we decided to override entries created by `google_dns_managed_zone` with `google_dns_record_set` resources to set proper TTL, and it seems to do the trick!

**Comment by danawillow** [comment]
Glad it worked! Going to close this out since the workaround seems like a reasonable one going forward.
