### ISSUE TITLE
Option to enable access to Composer's Private GKE Cluster

### ISSUE THREAD

**Issue by ChethanUK** [terraform-providers/terraform-provider-google#5422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

### Description

Need cidr range in Master authorized networks of Composer's GKE instead of `Master authorized networks Enabled`

### New or Affected Resource(s)

* google_composer_environment

* #0000

**Comment by venkykuberan** [comment]
@ChethanUK it looks to me [API](https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments#EnvironmentConfig) doesn't support that field yet. We will add the fields to provider once API support it. If you agree i will go head and close this issue.

**Comment by ChethanUK** [comment]
ya. Also, why is this error? `Private IP Composer Environment does not support Shared VPC` 
When we can create GKE in shared vpc? Also instead iof creating new K8s cluster for composer cant why can't we use existing gke only?

**Comment by venkykuberan** [comment]
You can't create a Cloud Composer environment using an existing GKE cluster because the cluster is created as part of the environment provisioning process, which associates that specific cluster with the environment (and also labels resources, etc).

`Caution: If you delete the GKE cluster that Cloud Composer uses, you must delete your environment, and create a new environment.`

Please refer this page : https://cloud.google.com/composer/docs/concepts/overview#google-kubernetes-engine.

I am closing this issue now as we can't do any action on our side. Please open an new issue in the future if the API supports the field and provider isn't.
