### ISSUE TITLE
Support region instance groups as resource

### ISSUE THREAD

**Issue by BrianPi** [terraform-providers/terraform-provider-google#5540]
I'd like to be able to create instance_groups which span a region. https://cloud.google.com/compute/docs/reference/rest/v1/regionInstanceGroups

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### New or Affected Resource(s)

* google_XXXXX

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.
```

### References

* #0000

**Comment by danawillow** [comment]
Hey @BrianPi, thanks for linking directly to the API docs! Unfortunately as you can see there, there isn't a create endpoint for RegionInstanceGroups- only get/list (which we already support via [this datasource](https://www.terraform.io/docs/providers/google/d/datasource_compute_region_instance_group.html).

The GCP docs at https://cloud.google.com/compute/docs/instance-groups#unmanaged_instance_groups seem to imply that this wouldn't be a recommended workflow, so I'm going to go ahead and close this since my best guess is that we're unlikely to see the ability to create these in the near future.
