### ISSUE TITLE
Decide on the implementation for source representation instance

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#5620]
https://github.com/GoogleCloudPlatform/magic-modules/pull/2871 and https://github.com/terraform-providers/terraform-provider-google/pull/3307 both propose adding roughly the same feature, but with significantly different implementations.

This issue is to track investigating the feature (https://cloud.google.com/sql/docs/mysql/replication/external-server#config-description) and deciding which implementation is the best fit for TPG.

**Comment by danawillow** [comment]
Taking a look through the docs, this seems like a good fit for a separate resource, despite using the same API endpoint and resource proto (and gcloud command). The only fields that overlap between source representation instances and regular cloud sql instances are Name, Region, and DatabaseVersion. It feels like a nicer UX to keep it as a separate instance rather than relying on a bunch of ConflictsWith and making sure users know which fields can be filled out in one type of instance vs another.

Both open PRs are for fixing https://github.com/terraform-providers/terraform-provider-google/issues/3704, but the one that uses a separate resource hasn't had any activity in a while. I'd like to close both open PRs, un-milestone the issue, and propose having someone on our team (probably me) work on it in Sprint 7 so that we're not just closing valid PRs without providing an alternative.
