### ISSUE TITLE
import google_compute_subnetwork unexpected behavior.

### ISSUE THREAD

**Issue by TraGicCode** [terraform-providers/terraform-provider-google#563]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- google_compute_subnetwork

### Actual Behavior
It blows up and says you need to do this and this does indeed work.

`terraform import google_compute_subnetwork.mynetwork us-east4/mysubnetwork`

### Steps to Reproduce
1. `terraform import google_compute_subnetwork.mynetwork my-subnetwork`

**Comment by rosbo** [comment]
Hi Michael,

This is working as expected. The documentation also says that you should use the `region/name` format. And the error message is also quite clear.

We used to support import for subnetwork by name only (we were scanning all networks behind the scene and try to find a subnetwork with that name). However, since two subnetworks can have the same name in two different regions, the user would get randomly one of the two. It lead to some confusion and we decided to require a more specific import string.
