### ISSUE TITLE
[doc][website] google_compute_region_target_http_proxy and google_compute_region_ssl_certificate are still in beta ?

### ISSUE THREAD

**Issue by tpoindessous** [terraform-providers/terraform-provider-google#5689]
Hi

Internal HTTPS Load Balancer is GA since 10 December : https://cloud.google.com/load-balancing/docs/release-notes#December_10_2019

But when I want to use google_compute_region_target_http_proxy / google_compute_region_target_https_proxy and google_compute_region_ssl_certificate objets, they are still in beta provider.

Is this normal ?

Thanks ! 

PS : my customer doesn't like using google-beta provider ;)

**Comment by rileykarson** [comment]
Hey @tpoindessous!

It's normal for features to have entered GA in GCP but not to have moved providers yet. We haven't got an automated process to promote resources / fields from Beta -> GA, mostly because the transition occasionally comes with behaviour changes or field renames that we need to handle manually to minimise the disruption for existing users.

We tend to GA fields when we do other work on the resource, or an enhancement request is filed asking to GA them. Would you mind [filing an enhancement](https://github.com/terraform-providers/terraform-provider-google/issues/new?template=enhancement.md) for the resources you're interested in? One per resource would be nice, but isn't required.
