### ISSUE TITLE
[data source] implementation google_compute_backend_bucket

### ISSUE THREAD

**Issue by bdronneau** [terraform-providers/terraform-provider-google#5690]
### Community Note

- Please vote on this issue by adding a +1 reaction to the original issue to help the community and maintainers prioritize this request.
- Please do not leave +1 or me too comments, they generate extra noise for issue followers and do not help prioritize the request.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment.
- If an issue is assigned to the modular-magician user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to hashibot, a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.20
+ provider.google v2.20.2
+ provider.google-beta v2.20.2

## Description

Hi,
I have shared [backend bucket](https://www.terraform.io/docs/providers/google/r/compute_backend_bucket.html) between my loadbalancers.
Like [backend service](https://www.terraform.io/docs/providers/google/d/datasource_google_compute_backend_service.html), I would like to know if there is any plan to implement `google_compute_backend_bucket` ?

Best

## New or Affected Resource(s)

- data_google_compute_backend_bucket

**Comment by bdronneau** [comment]
Hi,

I'll propose a PR.

**Comment by rileykarson** [comment]
Hey @bdronneau!

We've reserved backports for bugfixes in exceptional circumstances, generally when existing resources break due to changes in the underlying API soon after a major provider release. We use them to make sure that users aren't forced to perform a (possibly risky) migration so that their configs continue working.

I don't think that's something we'd do for a new datasource, unfortunately. If you'd like, you can run your amended `2.20.2` release including this datasource [from source](https://github.com/terraform-providers/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#running-a-local-copy-of-the-provider). Otherwise, you can [use an aliased provider block](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances) to mix the `3.X` datasource into the rest of your `2.X`-based config.

I'm going to close out https://github.com/terraform-providers/terraform-provider-google/pull/5699, and I'll get to https://github.com/terraform-providers/terraform-provider-google/pull/5700 sometime today.

**Comment by bdronneau** [comment]
Hi @rileykarson ,

Thank for answer.

Missing alias and version does not work from my testing in terraform. I already encountered this use case when playing with [module](https://www.terraform.io/docs/configuration/modules.html#module-versions)

In `providers.tf`:
```hcl
provider "google" {
  version = "~> 3.0"
  region = "europe-west2"
}

provider "google" {
  version = "~> 2.0"
  alias  = "west"
  region = "europe-west1"
}
```

Output:
```bash
terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

No provider "google" plugins meet the constraint "~> 2.0,~> 3.0".

The version constraint is derived from the "version" argument within the
provider "google" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: no suitable version is available
```

Too bad for the backport, I'll make a less automate version of our IAC and improve it when we bump in 3.x.

**Comment by rileykarson** [comment]
Huh! I'd assumed it worked, but looks like it's [intentional that it doesn't](https://github.com/hashicorp/terraform/issues/16641#issuecomment-344370704). If you're not already using `google-beta` you may be able to use that at a different version, since it's implemented as a different provider.
