### ISSUE TITLE
State migration

### ISSUE THREAD

**Issue by benpollardcts** [terraform-providers/terraform-provider-google#579]
Hi there,

I have just upgraded form tf version 0.9.7 to 0.10.7 and as such have moved to the plugin architecture. 

When running a plan terraform is complaining about my compute engine attached disks not using the new boot_disk, attatched_disk config options.

Am I correct in assuming I will not be able to use state migration as I've gone straight to version 1.0.1 of the plugin?

If I use an earlier version will I then be able to use the state migration of 1.0.1? Or should this just work now?

**Comment by danawillow** [comment]
Hey @benpollardcts, this should work. Are you still having issues?

**Comment by paddycarver** [comment]
Hi there! It's been a while since the issue opener replied, so in the interest of keeping the issues clean, I'm going to close this out. This helps the maintainers find the issues that require their attention and action, and speeds up development of the provider. If you feel this was closed in error, please feel free to reply to the issue. Thanks!
