### ISSUE TITLE
panic: interface conversion: interface {} is map[string]interface {}, not string

### ISSUE THREAD

**Issue by raddaoui** [terraform-providers/terraform-provider-google#6059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

terraform-provider-google v3.15.0

### Affected Resource(s)

* google_compute_region_disk_resource_policy_attachment

### Terraform Configuration Files

```
resource "google_compute_region_disk" "idm_persistent_disk" {
  provider = google-beta
  count                     = var.build_idm ? 1 : 0
  name                      = format("%s-%s-idm", var.idm_name, var.name)
  type                      = "pd-ssd"
  size                      = var.disk_size
  region                    = var.region
  physical_block_size_bytes = 4096
  replica_zones             = random_shuffle.idm_azs.result
  disk_encryption_key {
    kms_key_name = var.kms_key_id
  }
  labels = local.idm_labels
}
resource "google_compute_resource_policy" "disk_snapshot_policy" {
  count  = var.build_idm ? 1 : 0
  name   = format("%s-%s-snapshot-policy", var.name, var.idm_name)
  region = var.region
  snapshot_schedule_policy {
    schedule {
      hourly_schedule {
        hours_in_cycle = var.idm_disk_snapshot_interval
        start_time     = "23:00"
      }
    }
    retention_policy {
      max_retention_days    = var.idm_disk_snapshot_retention
      on_source_disk_delete = "APPLY_RETENTION_POLICY"
    }
    snapshot_properties {
      labels = merge({ "policy-purpose" = "persistent_disk_snapshot_policy" }, local.idm_labels)
    }
  }
}
resource "google_compute_region_disk_resource_policy_attachment" "attachment" {
  count  = var.build_idm ? 1 : 0
  name   = google_compute_resource_policy.disk_snapshot_policy[count.index].name
  disk   = google_compute_region_disk.idm_persistent_disk[count.index].name
  region = var.region
}
resource "google_compute_address" "idm_addresses" {
  count        = var.build_idm ? 1 : 0
  provider     = google-beta
  name         = var.idm_name
  address_type = "EXTERNAL"
  description  = "inputs_data_manager"
  network_tier = "PREMIUM"
  labels       = local.idm_labels
}
```

### Panic Output

https://gist.github.com/raddaoui/a79bc3e9825c3ca8938a4ad0868f2ab3

### Expected Behavior

google_compute_region_disk_resource_policy_attachment resource created

### Actual Behavior

panic

### Steps to Reproduce

Issue is intermittent, This works when we apply the resources normally  but fails when it gets into a certain state.

### References

resource_policy_attachment for google_compute_region_disk was recently created so there's no other references.

**Comment by venkykuberan** [comment]
@raddaoui i tried your config few times, resources created all the times without any issues. Can you attach the plan output or full debug log to get an idea what value passed caused the crash.
 Is the resource `google_compute_region_disk_resource_policy_attachment` causing the crash ?

**Comment by raddaoui** [comment]
yes the problem is intermittent and only happens in a certain state @venkykuberan 
this is the full debug log. I suspected that it was caused by `google_compute_region_disk_resource_policy_attachment` resource because the function that errored when panic happened is `resourceComputeRegionDiskResourcePolicyAttachmentDecoder()`
https://gist.github.com/raddaoui/94d3d39bd05719d988116cf34590f0a7

**Comment by megan07** [comment]
Hi @raddaoui!  I'm sorry you ran into this. It's very interesting. By looking at the code, I can understand how we might potentially run into that error, but with the understanding of the API (even with the response in the debug logs you've provided), I'm having a hard time figuring out what actually went wrong here.
There is a method that takes `resourcePolicies` from the API response and basically says if it's a list, keep it a list, but if it's a map, make a list where this map is the only item in the list.  This list is then passed to another function, where we try to retrieve the items.  The expectation in this specific case is that the items _should be_ strings (since that is what the API is returning), but in reality, we're allowing a list of maps.  My assumptions is that the value in the map is the value we're after, but without knowing what the key to that map is, I'm unable to retrieve that value.
Unfortunately, I'm unable to reproduce this.  I've tried a few times, but it seems to be working fine for me.  Are you able to give me any details of what sort of state it was in when you saw this error?  Or was there a special order of events taken before this happened?  Does it only happen on `apply` or do you see it with `plan` as well? Any other information that could be helpful in my being able to reproduce this would be very beneficial.
Thanks!

**Comment by raddaoui** [comment]
Hi @megan07 thanks for looking into it. we spent a long time debugging the problem and now I know how to reproduce it. it happens when you do terraform plan. and the issue basically was there were some orphaned google_compute_region_disk_resource_policy_attachment resources that were somehow deleted from GCP but they still exist in state file and once you do a terraform plan you will get that panic error from the gist file. so if you create the resources from the `Terraform Configuration Files` section above and then remove manually the resource policy attachement from the regional disk and try to do terraform plan again, it will fail and you will get the same error. I hope that helps to solve the issue and the fix will provide a clear, helpful message that a resource  policy attachment is missing

**Comment by megan07** [comment]
Hi @raddaoui !  Thank you so much for the feedback, I was able to reproduce it and put in the fix.  Thank you!
