### ISSUE TITLE
Support Google App Engine

### ISSUE THREAD

**Issue by mytototo** [terraform-providers/terraform-provider-google#638]
Hi,

I was looking for Terraform resources about Google App Engine. I can't find anything about it.
Am I missing something ? Is there any plan to support Google App Engine ?

Thanks.

**Comment by ctavan** [comment]
There's a draft-PR for creating app engine apps in https://github.com/terraform-providers/terraform-provider-google/pull/125 but it's fairly incomplete.

**Comment by arturaslayerv** [comment]
+

**Comment by paddycarver** [comment]
The beginning of our app engine support, the ability to create and manage apps, is added in #1503. We'll continue to add resources to better support App Engine, too.

**Comment by mytototo** [comment]
Thank you very much for your work (and for the update) @paddycarver.
Should we close this issue in favor of your PR?

**Comment by booi** [comment]
Great work!

**Comment by paddycarver** [comment]
I'd love to leave the issue open just so we can track the issue separately from the implementation of a fix. I'll come close the issue out when the PR (or a different PR adding the support, if we decide not to go with #1503) is merged.

**Comment by paddycarver** [comment]
Just merged in #1503, so I'm going to close this out, as it looks like the next release will have support for creating App Engine applications.

**Comment by sjungwirth** [comment]
Hi guys, first thanks for the great work on TF, its a great experience.

I wanted to comment here though I think the behavior of removing the app_engine config block could be better. Right now it thinks that TF should destroy the whole project and create it again.

I understand the reasoning is based on the fact that this is the only way to "remove" app engine from a project, but this will not actually ever work, as projects don't actually get deleted from GCP for maybe ~30 days. When TF "destroys" a project it just gets moved to a pending deletion status, and the real kicker, you can't create a new project with the same ID, because the old project with that same ID still exists.

I'm not sure if this would be considered a bug or not, but I can create a new issue if that is preferable, but I think the current behavior just doesn't make sense and to work around it I have to do manual state file editing.

**Comment by paddycarver** [comment]
I think definitely moving the conversation to a new issue is best, just so we can track it.

In the new issue, I'd love an outline of what you'd prefer to happen, instead.
