### ISSUE TITLE
Managing API keys

### ISSUE THREAD

**Issue by shouichi** [terraform-providers/terraform-provider-google#6413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

It seems like we can not manage API keys. We need to manage them to use Google Maps' geocoding API that requires an API key.

### New or Affected Resource(s)

* API Keys

### Potential Terraform Configuration

```tf
# Propose what you think the configuration to take advantage of this feature should look like.
# We may not use it verbatim, but it's helpful in understanding your intent.

resource "google_api_key" "key" {
	api_restrictions = [
		"geocoding",
		...,
	]
}
```

**Comment by emilymye** [comment]
In general, API keys with Google Cloud or other Google APIs are not creatable via Terraform because they only can be [created](https://developers.google.com/maps/documentation/geocoding/get-api-key) via the Cloud Console UI/web-app, not programatically using some API, and they tend to require OAuth2 authentication to create (i.e. your Google login), which we don't support in Terraform. 

I'm also not sure that this is a good idea anyways, since API keys for Google APIs tend to be long-lasting, identifying credentials specific to a user or group of users (human operators), and thus should be bootstrapped and managed like other root secrets rather than service account keys or other secrets, which were meant to be used by machines or programatically created/deleted (even if they are also long-lasting and identifying in practice :( )
