### ISSUE TITLE
google_bigquery_table expiration_time isn't handled correctly during table creation

### ISSUE THREAD

**Issue by Phlamethrower** [terraform-providers/terraform-provider-google#6509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.26
+ provider.google v3.24.0
```

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

```tf
provider "google" {
  project = "xxxx"
}

resource "google_bigquery_dataset" "dataset" {
  dataset_id = "test"
  default_table_expiration_ms = 86400000 # 1 day
}

resource "google_bigquery_table" "table" {
  dataset_id = google_bigquery_dataset.dataset.dataset_id
  table_id = "test"
  expiration_time = 0 # "never"
  schema = <<EOF
[
  {
    "name": "test",
    "type": "STRING",
    "mode": "NULLABLE"
  }
]
EOF
}
```

### Debug Output

https://gist.github.com/Phlamethrower/ce3b481ac4c6de005ad08bb4336816fb

### Expected Behavior

The table should be created with an expiration time of "never"

### Actual Behavior

The table is created with an expiration time of 1 day (the default for the dataset). Running `terraform apply` again will correct the error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Authenticating as a user.

**Comment by edwardmedia** [comment]
I can see below plan after the first apply
```

  # google_bigquery_table.table will be updated in-place
  ~ resource "google_bigquery_table" "table" {
        creation_time       = 1591108756209
        dataset_id          = "issue6509testds"
        etag                = "FiTkLoaKSe/V40AjB/zGcg=="
      ~ expiration_time     = 1591195156209 -> 0
        id                  = "projects/myproject/datasets/ssue6509testds/tables/issue6509testtb"
        labels              = {}
        last_modified_time  = 1591108756334
        location            = "US"
        num_bytes           = 0
        num_long_term_bytes = 0
        num_rows            = 0
        project             = "myproject"
        schema              = jsonencode(
            [
                {
                    mode = "NULLABLE"
                    name = "test"
                    type = "STRING"
                },
            ]
        )
        self_link           = "https://www.googleapis.com/bigquery/v2/projects/myproject/datasets/issue6509testds/tables/issue6509testtb"
        table_id            = "issue6509testtb"
        type                = "TABLE"
    }
```

**Comment by megan07** [comment]
Hi @Phlamethrower! This is interesting! I had to re-read this a few times to make sense of it, but I think this is something GCP has set.
>If you set the expiration when the table is created, the dataset's default table expiration is ignored. If you do not set a default table expiration at the dataset level, and you do not set a table expiration when the table is created, the table never expires and you must delete the table manually.
At any point after the table is created, you can update the table's expiration time

It appears that, on create, if nothing is set, its set to the default.  But on update, if nothing is set, its set to `Never`. Nothing says that explicitly, but that's how it appears to be working. 
I suppose there needs to be some way of differentiating the default from `Never`. And in Terraform, on update, if `expiration_time` is not set in the config, we send what's in state (the default). Whereas, if the config is set to `0`, we send nothing, which is why it works like this on update. Documentation is [here](https://cloud.google.com/bigquery/docs/managing-tables#updating_a_tables_expiration_time). I'll close this issue for now, but if you feel this doesn't adequately solve your issue, we can re-open and maybe raise the issue to the GCP BigQuery team.

**Comment by Phlamethrower** [comment]
OK, thanks for looking into it. For now, I can get the effect I want by setting an expiration time which is far in the future (e.g. year 3000).
