### ISSUE TITLE
Adding resource_policies to a google_compute_disk forces replacement of the disk

### ISSUE THREAD

**Issue by techwolf359** [terraform-providers/terraform-provider-google#6600]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Adding `resource_policies` to a `google_compute_disk` forces replacement of the disk. It should not - this can be an in-place operation.

* Terraform 0.12.9
* Google Provider 3.26.0

Running `terraform plan` after assigning `resource_policies` to an existing disk shows:
```
#... must be replaced
-/+ resource "google_compute_disk" "data-disk" {
...
      ~ resource_policies         = [ # forces replacement
          + "$POLICYNAME",
        ]
...
    }
```

There are methods that enable this to be done without rebuilding the disk, including `gcloud`:
```
$ gcloud compute disks add-resource-policies $DISKNAME --resource-policies=$POLICYNAME --project=$PROJECTNAME --zone=$ZONE
Updated [https://www.googleapis.com/compute/v1/projects/$PROJECTNAME/zones/$ZONE/disks/$DISKNAME].
```

### New or Affected Resource(s)

* google_compute_disk

### Potential Terraform Configuration

(No change)

**Comment by emilymye** [comment]
This is an interesting case that I don't think we document very well - we actually support this as a different resource [`google_compute_disk_resource_policy_attachment`](https://www.terraform.io/docs/providers/google/r/compute_disk_resource_policy_attachment.html). We support it this way for a few reasons, but mostly because the [API method](https://cloud.google.com/compute/docs/reference/rest/v1/disks/addResourcePolicies) to update the disk policies only supports one policy being added/removed at a time (currently). It might be a good idea to document this in the disk resource docs.
