### ISSUE TITLE
Confused about the status of Firestore support

### ISSUE THREAD

**Issue by kentcb** [terraform-providers/terraform-provider-google#6602]
I'm trying to understand how much of my infrastructure I can automate with Terraform. I need to stand up several GCP projects with Firestore enabled, and preferably be able to create a default document or two.

I'm able to create the GCP projects via `google_project` and `google_firebase_project`, but from there I'm stuck. There's a `google_firestore_index` resource, but that seems to assume that Firestore has already been enabled on the project, which I can't find a way to do via Terraform.

I am also aware of [this open issue](https://github.com/terraform-providers/terraform-provider-google/issues/3657), which is to enable document creation. I can live without that for now, but I'd _really_ like to be able to turn on Firestore in a specific region on my GCP projects. Am I right in saying Terraform can't do this yet?

**Comment by salrashid123** [comment]
pr https://github.com/terraform-providers/terraform-provider-google/pull/6598  would allow you to create a firestore or datastore instance on a new project

**Comment by emilymye** [comment]
@kentcb It's a bit confusing since we split the issue into two but https://github.com/terraform-providers/terraform-provider-google/issues/3657 is actually meant to manage the project-level enabling of Firestore, whereas https://github.com/terraform-providers/terraform-provider-google/issues/3950 is for document level. I'd follow #3657, which may get resolved soon :)

**Comment by kentcb** [comment]
Exciting! Thanks @salrashid123 & @emilymye.
