### ISSUE TITLE
Cloud Run Deployment not updating when Docker image changes

### ISSUE THREAD

**Issue by dlorch** [terraform-providers/terraform-provider-google#6706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.12.26

### Affected Resource(s)

* google_cloud_run_service 

### Terraform Configuration Files

Assume the following TF code from the example on https://www.terraform.io/docs/providers/google/r/cloud_run_service.html

```tf
resource "google_cloud_run_service" "default" {
  name     = "cloudrun-srv"
  location = "us-central1"

  template {
    spec {
      containers {
        image = "gcr.io/cloudrun/hello"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}
```

### Expected Behavior

In subsequent runs of `terraform apply`, when the image at the location `gcr.io/cloudrun/hello` updates or changes, I expect the Cloud Run deployment to update to the latest image.

I also tried with `gcr.io/cloudrun/hello:latest` but that did not change the behavior.

### Actual Behavior

In subsequent runs of `terraform apply`, when the image at the location `gcr.io/cloudrun/hello` updates or changes, I the Cloud Run deployment does not update to the latest image.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform apply`

### References

**Comment by venkykuberan** [comment]
Terraform isn't aware of changes happening in the image repository, the config has to reflect that. When there is a change in the config terraform picks the diff and tries to the inplace update for the resource. Just added plan output for reference.

```

          ~ spec {
                container_concurrency = 80

              ~ containers {
                    args    = []
                    command = []
                  ~ image   = "gcr.io/cloudrun/hello" -> "gcr.io/cloudrun/hello:latest"

                    resources {
                        limits   = {
                            "cpu"    = "1000m"
                            "memory" = "256Mi"
                        }
                        requests = {}
```

**Comment by dlorch** [comment]
Thank you for reviewing the issue. Yes, I understand that. The use case I have is: `terraform apply` is executed each time my project's repository is `git push`-ed. The project repository consist of both the application code and the terraform manifests. If there are changes in the application code, the Docker image will be re-built, but the new application version will __not__ be re-deployed to Cloud Run because of exactly the steps you described.

An alternate approach I tried was to use `google_container_registry_image` to obtain the `digest` of the `latest` image, so I could append it to the image reference above. But 

```
data "google_container_registry_image" "hello_image" {
  name = "gcr.io/cloudrun/hello"
}
```

returns and empty value for `hello_image.digest`.

I understand your logical explanation, but I feel it's not doing what a user would expect it should be doing. Do you see my viewpoint on this? I would prefer to continue to use Terraform for Cloud Run and not resort to `gcloud` commands for the deployment, but don't see a way how I could do it.

**Comment by dlorch** [comment]
Here's an idea on how Terraform could handle this situation: given an image definition like "gcr.io/cloudrun/hello:latest", Terraform could transparently look up the "latest" tag and store the respective digest in its own state file. On subsequent runs, Terraform would then discover that the underlying image has changed and do the right thing.

**Comment by c2thorn** [comment]
Hi @dlorch, 
You have a totally reasonable viewpoint, and I believe there is a way to get what you need. See: https://github.com/terraform-providers/terraform-provider-google/issues/6635

`google_container_registry_image` is completely offline because GCP doesn't provide a way to read docker info. Essentially, you'll want to use the [docker provider](https://www.terraform.io/docs/providers/docker/d/registry_image.html) to read your image, then reference the digest in `google_container_registry_image` to build the url/name, then reference that name within your cloud build service. There may be alternative ways to do this, but you'll want to pull using the docker provider either way.

If the docker provide reads a change in the digest, `google_cloud_run_service` will detect a change in the `image` field and redeploy.

**Comment by felimartina** [comment]
Alternatively, 
You could use multiple tags instead of defaulting to `latest`. You can have an image tagged as `latest` and `1.0.0`. Then use the version tag within terraform, that way everytime you bump your version terraform will detect a change in the image and re-deploy a new revision. Obviously, you will need a way to read the version number in Cloud Build and pass it on as argument to terraform...which is totally doable.

**Comment by dlorch** [comment]
@c2thorn thank you very much, I can confirm the approach with the docker_registry_image works: https://github.com/dlorch/errors.fail/commit/a6b8381f18dae797ae5fd225c390b21eda981f31

@felimartina thank you too for your suggestions, I was considering this as an alternate option.
