### ISSUE TITLE
Cloud IoT Core Device resource documentation page is missing

### ISSUE THREAD

**Issue by ferrarimarco** [terraform-providers/terraform-provider-google#6855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

`0.12.29` (doesn't actually matter)

### Affected Resource(s)

* google_cloudiot_device

Possibly others?

### Expected Behavior

Documentation for `google_cloudiot_device` should be available at https://www.terraform.io/docs/providers/google/r/cloudiot_device.html. Markdown is [correctly generated](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/docs/r/cloudiot_device.html.markdown), and the [link is in the menu](https://github.com/terraform-providers/terraform-provider-google/blob/master/website/google.erb#L593).

### Actual Behavior

https://www.terraform.io/docs/providers/google/r/cloudiot_device.html gives a 404, and the link is not available in the resoureces menu.

### Steps to Reproduce

1. Open https://www.terraform.io/docs/providers/google/ with your browser
1. Look for the Cloud IoT Core device resource

### Important Factoids

I've seen the page in the past days, so maybe a change broke something?

### References

N/A (for now)

**Comment by rileykarson** [comment]
Thanks for the bit about the page being available before- that helped narrow it down!

We made a [`3.29.1` release of `google-beta`](https://github.com/terraform-providers/terraform-provider-google-beta/releases/tag/v3.29.1) that unintentionally overwrote the website (which is based on `google-beta`) with an older revision. We're doing our next release (`3.32.0`) in the next couple of hours, so the page should show back up then. In the meantime though, it's also [available on the Registry](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudiot_device).

Since there's nothing that needs to be done specifically for this bug, I'm going to optimistically close it out. If the page is unavailable tomorrow, please feel free to comment here / reopen it!

**Comment by ferrarimarco** [comment]
@rileykarson the page is back online! Thanks.

Maybe it's a chance to add a sanity check to prevent this in MM? WDYT?

**Comment by rileykarson** [comment]
There isn't much MM can do! The issue comes from how HashiCorp's provider release tooling works. It was built for a monotonous series of releases over time, with each release being a superset of the last. As such, it automatically overwrites the website with the latest release.

While performing a backport we accidentally overwrote the website with the old one. I think we missed an argument in the release command that would have stopped that happening, but I'm not sure.

This will all be resolved when providers move to the registry. It doesn't keep a single website per provider, but actually holds the website per {provider, release} pair.
