### ISSUE TITLE
Support for regional rather than zonal clusters

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#829]
Hey,
Is there anything on your roadmap to support regional clusters?
https://cloudplatform.googleblog.com/2017/12/with-Google-Kubernetes-Engine-regional-clusters-master-nodes-are-now-highly-available.html

I'm sure MANY people would like highly available masters!

**Comment by Stono** [comment]
@rosbo does the upstream tag mean it's coming? :-)

**Comment by homelessnessbo** [comment]
@Stono I'm not a developer of terraform, but I've spent few hours trying to investigate if it's easy to contribute this feature (because it sounds like this) and I've realised that all the code of `google_container_cluster ` resource is based on `v1` stable API and regional clusters are available only in `v1beta` API version, which makes implementation a little bit hard, because mechanic of working with `v1beta` a little bit differs from `v1`, so I wouldn't expect this in the next release ( but I really need this feature too ). 
Anyway I'm going to spend some time trying to contribute it by myself this week, but I can't promise anything :)

**Comment by Stono** [comment]
@homelessnessbo just wondering how you're getting on with this or if you could share your WIP?
We have some people here who may be able to assist

**Comment by homelessnessbo** [comment]
@Stono sorry, but I've met a few more limitations in terraform that blocks me and switched to Google Cloud Deployment Manager with it's jinja2 templates that are way more flexible (IMO). But GCDM also doesn't support beta api for container.clusters (https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types), so ¯\_(ツ)_/¯.

**Comment by a13x212** [comment]
Any updates on this issue? This has become a blocker to use terraform within our organization.

**Comment by danawillow** [comment]
Added in #1181.
