### ISSUE TITLE
Add Bucket IAM policy resource

### ISSUE THREAD

**Issue by rolandkool** [terraform-providers/terraform-provider-google#843]
Hi,

Version 1.4.0 comes with support for Bucket IAM member and binding, which is great! It would be nice to also have the policy variant where you apply one policy to a bucket overriding all other applied policies. Similar to what you can do on a project with the google_project_iam_policy.

Our use case requires that we don't want allow to any manual changes to policies so if one is to manually change the buckets IAM it would be reverted with a terraform run.

Thanks

**Comment by rosbo** [comment]
Hi @rolandkool 

The reason I did not add a `google_storage_bucket_iam_policy` resource is because there is a bunch of legacy roles that are automatically added when creating a policy.

There is different ways we can handle these:
1. Always ignore these roles. You cannot set or remove them when using the authoritative iam_policy resource.
2. A user has to specify these legacy roles in their config otherwise they will get deleted.

The main advantage of 2 is that users can manage legacy roles if they want to. The main disadvantage is that it is tiny bit more verbose to keep them.

I personally tend to prefer 2. I am curious about your opinion on the subject.

Thank you

**Comment by rolandkool** [comment]
Hi @rosbo 

For me, option 2 is fine and expected. For default rules we want to keep, we will just make sure to add them in the policy as well. For project policy bindings, we are doing the same.

**Comment by paddycarver** [comment]
I believe this was addressed by #1190. If not, feel free to comment, and we can reopen this!
