### ISSUE TITLE
Valid GKE cluster version reported as invalid

### ISSUE THREAD

**Issue by adam-sandor** [terraform-providers/terraform-provider-google#877]
We are repeatedly running into issues with specifying the right version of Kubernetes for GKE clusters. Versions that are valid one day become invalid after some time even though they are listed in the dropdown on the GCP Console UI. It also looks like the invalid version can be used if we are upgrading the cluster but not when creating a new cluster.

### Terraform Version
Terraform v0.11.0
+ provider.google v1.4.0
+ provider.null v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- google_container_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "google_container_cluster" "primary" {
    project = "${var.project_id}"
    name = "${var.cluster_name}"
    zone = "${var.zone}"
    initial_node_count = 1
    #enable_legacy_abac = false
    network = "${google_compute_network.tenant-network.name}"
    subnetwork = "${google_compute_subnetwork.tenant-subnet.name}"

    node_version = "1.8.4-gke.0"
    min_master_version = "1.8.4-gke.0"
    node_config {
        machine_type = "g1-small"
        disk_size_gb = 50
        oauth_scopes = [
            "https://www.googleapis.com/auth/compute",
            "https://www.googleapis.com/auth/devstorage.read_write",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring",
            "https://www.googleapis.com/auth/pubsub",
            "https://www.googleapis.com/auth/cloud-platform"
        ]
    }
}
```

### Expected Behavior
Create a GKE cluster with version `1.8.4-gke.0`. I can see that this version is available in the dropdown in the GKE Console UI for my project.

### Actual Behavior
`google_container_cluster.primary: googleapi: Error 400: Version "1.8.4-gke.0" is invalid., badRequest`

### Steps to Reproduce
1. `terraform apply`

**Comment by Stono** [comment]
It's not available any more, it's not a terrarorm version, you can't even
do it through the gui!

Change to .1

On 19 Dec 2017 4:35 pm, "Ádám Sándor" <notifications@github.com> wrote:

We are repeatedly running into issues with specifying the right version of
Kubernetes for GKE clusters. Versions that are valid one day become invalid
after some time even though they are listed in the dropdown on the GCP
Console UI. It also looks like the invalid version can be used if we are
upgrading the cluster but not when creating a new cluster.
Terraform Version

Terraform v0.11.0

   - provider.google v1.4.0
   - provider.null v1.0.0

Affected Resource(s)

Please list the resources as a list, for example:

   - google_container_cluster

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.
Terraform Configuration Files

resource "google_container_cluster" "primary" {
    project = "${var.project_id}"
    name = "${var.cluster_name}"
    zone = "${var.zone}"
    initial_node_count = 1
    #enable_legacy_abac = false
    network = "${google_compute_network.tenant-network.name}"
    subnetwork = "${google_compute_subnetwork.tenant-subnet.name}"

    node_version = "1.8.4-gke.0"
    min_master_version = "1.8.4-gke.0"
    node_config {
        machine_type = "g1-small"
        disk_size_gb = 50
        oauth_scopes = [
            "https://www.googleapis.com/auth/compute",
            "https://www.googleapis.com/auth/devstorage.read_write",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring",
            "https://www.googleapis.com/auth/pubsub",
            "https://www.googleapis.com/auth/cloud-platform"
        ]
    }
}

Expected Behavior

Create a GKE cluster with version 1.8.4-gke.0. I can see that this version
is available in the dropdown in the GKE Console UI for my project.
Actual Behavior

google_container_cluster.primary: googleapi: Error 400: Version
"1.8.4-gke.0" is invalid., badRequest
Steps to Reproduce

   1. terraform apply

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/terraform-providers/terraform-provider-google/issues/877>,
or mute the thread

**Comment by Stono** [comment]
Terrarorm problem *

**Comment by adam-sandor** [comment]
Yes, using 1.8.4-gke.1 works. .0 is still visible in the UI for me btw but I think this time it's a simple upgrade issue and not the weird problem we were experiencing before. You can close the issue.
