### ISSUE TITLE
google_compute_backend_service: Please support some way to have non-existing backend groups

### ISSUE THREAD

**Issue by waldiTM** [terraform-providers/terraform-provider-google#925]
Hi

I have a module that sets up a global load balancer in the Google cloud. Backends for it are distributed over several regions. So the `google_compute_backend_service` lists quite a few backend groups (ten right now).

Now I would like to setup a reduced version of this as test environment. In this setup only one region is used for backends. However all backend groups referenced in the `google_compute_backend_service` resource still need to exist, even if no backends exists within them. It is not possible to provide a (possibly empty) list as backend self-link.

Please provide some way to disable backend groups.

### Terraform Version
```
Terraform v0.11.1
+ provider.google v1.4.0
```

### Affected Resource(s)
- google_compute_backend_service

### Terraform Configuration Files
```hcl
resource "google_compute_backend_service" "main" {
  name = "main"
  port_name = "http"
  protocol = "HTTP"
  timeout_sec = 120

  backend {
    group = "${module.backend-asia-east1-a.group.main}"
  }
  backend {
    group = "${module.backend-asia-east1-c.group.main}"
  }
  backend {
    group = "${module.backend-asia-northeast1-a.group.main}"
  }
  backend {
    group = "${module.backend-asia-northeast1-b.group.main}"
  }
[...]
}
```

**Comment by rosbo** [comment]
We could discard the backend if the group is empty.

However, I am wondering if the new HCL2 language will support adding conditional around the whole `backend` block. @paddycarver do you know if this is a use case supported by the new config language?

**Comment by paddycarver** [comment]
Apologies for the delay on this. Let me see if I'm following correctly, and then I can try to propose some solutions.

* You've got a single `google_compute_backend_service` that has N `backend` blocks, where N is any arbitrary number greater than 1.
* This is in a module or some other parameterized form that makes it suitable for reuse across environments.
* I'm unsure about this bit, clarification would help: as part of that reuse, you're passing in a list of backends to use? Or are you only specifying each backend as a separate variable? Or are you setting something like "multiregion: true" or similar?
* I'm unsure about this bit, clarification would help: you want the backends created, even if they have no backend group? Or do you not care, the important part is that the same config works for variable numbers of backend groups?

Based on my current understanding (you don't care whether the empty backends exist or not, you just want to be able to use the same config for variable numbers of backends) the ideal solution would be to have conditional blocks supported, which is something I know everyone is interested in, the core team included, but I wouldn't block implementation on it. More information here: hashicorp/terraform#7034

In the immediate case, I think we could work around this by allowing the backend to not be set, as @rosbo said, but given there's a clearer design decision we have in mind to solve this problem, I'd want to do so in a way that allows us to switch to the better design when it's possible, without disrupting users too much. To that end, I'd propose if we _do_ make it possible to specify an empty string as a backend, we do so by adding another field to the backend called `allow_empty` or something similar, that only accepts an empty string when it's set to true. That way we can print a deprecation message when it's time to make the switch, and we can have a graceful deprecation that clearly communicates what's going on instead of abruptly subtly changing behavior on users with no good way to communicate that.

Does that sound like a reasonable way forward?

**Comment by waldiTM** [comment]
I have
* one module that creates a `google_compute_instance_group` ([implementation](https://gitlab.com/waldi/debian-mirror-cloud-terraform/blob/master/gce/archive/backend/instances.tf)) per zone,
* a parent module that references all the groups into one `google_compute_backend_service` ([implementation](https://gitlab.com/waldi/debian-mirror-cloud-terraform/blob/master/gce/archive/backend/instances.tf)).

This produces a lot of instance groups with zero instances, as I have to hard-code all zones that are used in any of my environments.

I would like to stop creating all this zero instance `google_compute_instance_group` resources.

**Comment by vaijab** [comment]
Just to add some noise to this issue. I have exact same problem.

**Comment by paddycarver** [comment]
I'm looking through your linked repo (both implementation links lead to the same file, which doesn't use `module`) and notice you have `count` set conditionally on the instance group. So it seems you already have a way to avoid creating the instance group? I feel like I'm missing a key part of the problem statement.

From what I understand:

* You want to create a `google_compute_instance_group` per zone, and can
* You want to have a parent module that references all the groups into a backend service, and can
* This produces a lot of instance groups with zero instances <--- this part I don't understand, because it looks like you're setting count to 0 if no instances would be created, which should mean no instance group actually gets created

For that last point, are you saying you don't want the instance in the terraform state? Or is it actually creating an instance group with target instance count set to 0 in Google Cloud?

**Comment by waldiTM** [comment]
If you take a look into the documentation of [`google_backend_service`](https://www.terraform.io/docs/providers/google/r/compute_backend_service.html) (code works also), you'll see that the backend group link is required. I can drop the `google_compute_instance_group` objects, but I can't remove the reference to it in the backend service.

**Comment by paddycarver** [comment]
OK, so I think I'm following here. For future-me (or others trying to understand the problem):

* There's no problem with setting `count = 0` on `google_compute_instance_group`
* The module returns the `self_link` of the `google_compute_instance_group` (using splat, I assume, to return an empty list when none is created, instead of an error?)
* `google_backend_service`'s `backend` block is optional, but if it's specified, the `group` _must_ be set on it. <-- this is where the problem is

We have no way of doing conditional blocks at the moment, so we _have_ to provide a `backend` block for every _potential_ backend, even though we may not actually be using some.

The module stuff is really a red herring--this would be the same if it was all in one module, and the user was just specifying instance counts for each zone. We just need a way to conditionally set the `backend` blocks on the `instance_group`.

Now that I'm following, I'm more-or-less in agreement with @rosbo's suggestion that we ignore the `backend` block if the `group` attribute is empty. However, because this is a breaking change, and because I can see it being a source of confusion and bugs for users in the future, I'd like to make it available only as an opt-in, by adding a `ignore_if_group_empty` or similar attribute.

Then your use case (I believe!) could be achieved by setting the `ignore_if_group_empty` attribute to `true`, and having the module return either the `group`'s `self_link` or `""`, depending on whether the group should be created or not.

Does that work for you, @waldiTM?

**Comment by waldiTM** [comment]
I missed that response, sorry about that.

Yep, just ignoring empty groups would work for me.

**Comment by danawillow** [comment]
This issue hasn't been active in a while, but I wanted to follow up for anyone that's still subscribed to it. Terraform 0.12 brought with it the addition of dynamic blocks, which allow for solving this sort of issue without any provider-side changes.

In this particular case, something like this may work (I haven't actually tested it so it probably needs some tweaking, but this is the general idea):
```hcl
resource "google_compute_backend_service" "main" {
  name = "main"
  port_name = "http"
  protocol = "HTTP"
  timeout_sec = 120

  dynamic "backend" {
    for_each = module.backend-asia-east1-a.group.main
    content {
      group = "backend.self_link"
    }
  }
  ...
}
```

where `module.backend-asia-east1-a.group.main` sets `count = 0` or `count = 1` depending on whether it should be enabled or not.

Hope this helps! I'm going to close out this issue, but if there are any provider-side bugfixes or feature requests that still would be useful to have relating to this issue, please file a new one with the appropriate template filled out.
