### ISSUE TITLE
Add import command for bigtable

### ISSUE THREAD

**Issue by wmuizelaar** [terraform-providers/terraform-provider-google#932]
### Terraform Version
0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- google_bigtable_instance
- google_bigtable_table

### Expected Behavior
I can import the resources on my tfstate

### Actual Behavior
Import is not supported for resource: <resource>

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import <resource> xxxx`

**Comment by Legogris** [comment]
@wmuizelaar The issue description is confusing to me - is this a reference to an issue on another tracker?
This is something we would like to have. @paddycarver I was considering looking into this as a first contribution and getting inside TF - anything particular that makes this a breaking change?

**Comment by wmuizelaar** [comment]
@Legogris I definitely copy-pasted too much - editted the description to fit better :)

**Comment by rileykarson** [comment]
Hey @Legogris! 

For a bit of context: We don't currently support import because the (`v1`) API at the time that we implemented the feature didn't expose enough information to do so. There is now a `v2` API that *should* have that information looking over it briefly, because it also introduces clusters in addition to instances & tables.

Cloud Bigtable is also using a different API client than most of the provider. We normally use the [Go REST api clients](https://github.com/googleapis/google-api-go-client) but Cloud Bigtable is only supported by a [Cloud Client Library](https://github.com/GoogleCloudPlatform/google-cloud-go). This means that some of the patterns in the rest of the codebase aren't very useful to reference.

It's definitely on my (personal) radar to look at our Cloud Bigtable support and bring it up to date with the `v2` API, but I haven't had the time to sit down and work out how to get it there (and have no timeline/estimate for when I will unfortunately 🙁 ).

---

If import support is really important for you, we will gladly accept a community contribution here! I just wanted to be transparent that `"Here be dragons"` and that it may not be a great candidate for a first contribution. You would be working with a different client than the rest of the provider & `google_bigtable_instance` is an amalgam of an instance and a cluster and it may a little grungy to get all the right fields in the right place without introducing any breaking changes.

**Comment by psalaberria002** [comment]
Any news on this one? We migrated all of our codebase to 0.12, and the only service we have left is Bigtable. Is there any workaround for importing a cluster?

**Comment by rileykarson** [comment]
Other than manual remediation of state, not really. I'm likely picking up a general goal next quarter to improve the UX for Bigtable resources, which would include import. There should be news by EOQ depending exactly what order that work falls in.

**Comment by memory** [comment]
more than a quarter later -- any update on this?

**Comment by rileykarson** [comment]
This is assigned to me to complete by EOQ, I'm hoping to get to it soon after HashiConf.

**Comment by rileykarson** [comment]
Some fields aren't exposed in the client library that are needed to import the resource. I've made a change upstreaming one so far- once I can get https://code-review.googlesource.com/c/gocloud/+/45770 to land, I have a PR drafted locally which will add support for `google_bigtable_instance`. 

`google_bigtable_table` will follow after that, I may need to expose fields upstream in the client lib for that as well.

**Comment by nickmoorman** [comment]
Hi @rileykarson!  Just curious if you had any update on `google_bigtable_table` import support, and if you're also working on import functionality for `google_bigtable_gc_policy`.

**Comment by rileykarson** [comment]
`google_bigtable_table` will have import support in `2.20.0`, ~midway next week probably. Sorry for how drawn out resolving this was!

`google_bigtable_gc_policy` isn't currently possible to support, the client library only lets us read back a string representation of the GCPolicy. While we could modify the client again, it's less clear-cut of a modification than the change with instances/clusters.

Given that, I'm going to close out this issue based on having instance/table supported. Please open a new issue if anyone is interested in import support for GCPolicy!
