### ISSUE TITLE
provider project alias

### ISSUE THREAD

**Issue by dolvany** [terraform-providers/terraform-provider-google#949]
Terraform v0.11.1
+ provider.google v1.4.0

I would like to keep some Cloud DNS records in sync across multiple projects. Should provider aliases work for this purpose? Here is the config that I am attempting to use.

provider "google" {
  region      = "somewhere"
  project     = "proj1"
  credentials = ".secret.json"
}
provider "google" {
  alias      = "two"
  project     = "proj2"
}
provider "google" {
  alias      = "three"
  project     = "proj3"
}
resource "google_dns_record_set" "whatev" {
  name = "whatev.somezone.com."
  type = "A"
  ttl = 300
  rrdatas = ["1.1.1.1"]
  managed_zone = "somezone"
}

**Comment by danawillow** [comment]
Hey @dolvany, I don't think provider aliases is what you want here. In order to use provider aliases, you specify which provider you're planning to use in the resource itself: https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances. It sounds like your goal is to have three projects, each with a dns record set resource, is that correct? If so, you could use variables:
```
variable "projects" { type = "list" }
resource "google_dns_record_set" "whatev" {
  count = "${length(var.projects)}"
  project = "${var.projects[count.index]}"
  // everything else stays the same
}
```
Does that sound like what you're trying to do?

**Comment by rosbo** [comment]
The approach proposed by @danawillow seems sensible to me assuming we understood your problem correctly.

If that is not the case, feel free to reopen this issue and explain a bit more your use case.

Thank you
