### ISSUE TITLE
Setting project explicitly doesn't work on IAM resources

### ISSUE THREAD

**Issue by Stono** [terraform-providers/terraform-provider-google#993]
Hey:

This doesn't work
```
resource "google_project_iam_member" "project" {
  project = "k8-discovery-185615"
  role    = "roles/${google_project_iam_custom_role.gcr-viewer.role_id}"
  member  = "user:karl.stoney@autotrader.co.uk"
}
```
It gives you this:
```
* google_project_iam_member.project: Error applying IAM policy for project "k8-discovery-185615": Error setting IAM policy for project "k8-discovery-185615": googleapi: Error 400: Role roles/gcr.viewer is not supported for this resource., badRequest
```

Whereas this does:
```
resource "google_project_iam_member" "project" {
  project = "k8-discovery-185615"
  role    = "projects/k8-discovery-185615/roles/${google_project_iam_custom_role.gcr-viewer.role_id}"
  member  = "user:karl.stoney@autotrader.co.uk"
}
```

The actual terraform file is running against a different project (which is why i explicitly specify the project on the resource), I'm guessing it isn't being interpolated correctly

**Comment by danawillow** [comment]
Hey @Stono, thanks for the issue! The interpolation is actually working fine, but custom roles have to be specified with the project. Note what happens if you run `gcloud iam list-grantable-roles //cloudresourcemanager.googleapis.com/projects/PROJECT_ID`. Standard roles look something like this:
```
description: Full access to topics, subscriptions, and snapshots.
name: roles/pubsub.admin
title: Pub/Sub Admin
```
Notice here that the name is `roles/{role-name}`.

Whereas custom ones look like this:
```
description: A description
etag: BwVjZROqPmM=
name: projects/graphite-test-danahoffman-tf/roles/myCustomRole
stage: GA
title: My Custom Role
```
Notice here that the name is `projects/{project-id}/roles/{role-name}`

The name of the role includes the project, which is why the second way of doing it worked for you. In Terraform we don't have any way of knowing whether the role you provided was custom or not (since its name has already been interpolated by the time it reaches the `google_project_iam_member` resource), so we can't do any fancy manipulation- we have to just send the name back that's given to us.

Hope that makes sense! I'll see if I can clarify things in the docs.
